### ISSUE TITLE
mailcatcher failed to start

### ISSUE THREAD

**Issue by kforsthoevel** [sj26/mailcatcher#155]
Following the installation instructions I get this error on Ubuntu 12.04 and Ubuntu 14.04:
```
$ mailcatcher 
/opt/rbenv/versions/2.1.2/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- i18n/core_ext/string/interpolate (LoadError)
	from /opt/rbenv/versions/2.1.2/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /opt/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/activesupport-3.2.19/lib/active_support/core_ext/string/interpolation.rb:2:in `<top (required)>'
	from /opt/rbenv/versions/2.1.2/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /opt/rbenv/versions/2.1.2/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /opt/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/activesupport-3.2.19/lib/active_support/core_ext/string.rb:9:in `<top (required)>'
	from /opt/rbenv/versions/2.1.2/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /opt/rbenv/versions/2.1.2/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /opt/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/activesupport-3.2.19/lib/active_support/core_ext.rb:2:in `block in <top (required)>'
	from /opt/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/activesupport-3.2.19/lib/active_support/core_ext.rb:1:in `each'
	from /opt/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/activesupport-3.2.19/lib/active_support/core_ext.rb:1:in `<top (required)>'
	from /opt/rbenv/versions/2.1.2/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /opt/rbenv/versions/2.1.2/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /opt/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/mailcatcher-0.5.12/lib/mail_catcher.rb:1:in `<top (required)>'
	from /opt/rbenv/versions/2.1.2/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /opt/rbenv/versions/2.1.2/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /opt/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/mailcatcher-0.5.12/bin/mailcatcher:3:in `<top (required)>'
	from /opt/rbenv/versions/2.1.2/bin/mailcatcher:23:in `load'
	from /opt/rbenv/versions/2.1.2/bin/mailcatcher:23:in `<main>'
```
List of installed gems:
```
$ gem list --local

*** LOCAL GEMS ***

activesupport (3.2.19)
bigdecimal (1.2.4)
bundler (1.6.1)
daemons (1.1.9)
eventmachine (1.0.3)
haml (4.1.0.beta.1)
i18n (0.7.0.beta1)
io-console (0.4.2)
json (1.8.1)
mail (2.6.1)
mailcatcher (0.5.12)
mime-types (2.3)
minitest (4.7.5)
multi_json (1.10.1)
psych (2.0.5)
rack (1.6.0.beta)
rack-protection (1.5.3)
rake (10.1.0)
rdoc (4.1.0)
sinatra (1.4.5)
skinny (0.2.3)
sqlite3 (1.3.9)
test-unit (2.1.2.0)
thin (1.5.1)
tilt (1.4.1)
```
Any ideas?

**Comment by paulbeattie** [comment]
This works for me out the box running Ruby 2.2.0 and letting Rubygems install i18n 0.7.0. It seems that it could be related to i18n v0.7.0 going final.

**Comment by sj26** [comment]
Yep. Please remove any beta versions of i18n if you encounter this issue.

**Comment by bergerjac** [comment]
@CamJN the link in [your comment](https://github.com/sj26/mailcatcher/issues/155#issuecomment-61494096) is broken

**Comment by sj26** [comment]
@jondoe1337 that looks like you've got activesurpport 4.2.7.rc1 installed which is causing havoc. Can you try:

```
gem uninstall activesupport -v 4.2.7.rc1
```

**Comment by jondoe1337** [comment]
That worked for me - i replaced the version above with:

```
gem install activesupport -v 4.2.6
```

Thanks!
