### ISSUE TITLE
Ubuntu 14.04, RVM, can't start mailcatcher

### ISSUE THREAD

**Issue by danylevskyi** [sj26/mailcatcher#164]
I'm trying to install mailcatcher with RVM.

```
rvm default@mailcatcher --create do gem install mailcatcher
rvm wrapper default@mailcatcher --no-prefix mailcatcher catchmail
```

Installation goes well. But after starting mailcatcher I get next errors:

```
/home/dmytro/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- i18n/core_ext/string/interpolate (LoadError)
        from /home/dmytro/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /home/dmytro/.rvm/gems/ruby-2.1.2@mailcatcher/gems/activesupport-3.2.19/lib/active_support/core_ext/string/interpolation.rb:2:in `<top (required)>'
        from /home/dmytro/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /home/dmytro/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /home/dmytro/.rvm/gems/ruby-2.1.2@mailcatcher/gems/activesupport-3.2.19/lib/active_support/core_ext/string.rb:9:in `<top (required)>'
        from /home/dmytro/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /home/dmytro/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /home/dmytro/.rvm/gems/ruby-2.1.2@mailcatcher/gems/activesupport-3.2.19/lib/active_support/core_ext.rb:2:in `block in <top (required)>'
        from /home/dmytro/.rvm/gems/ruby-2.1.2@mailcatcher/gems/activesupport-3.2.19/lib/active_support/core_ext.rb:1:in `each'
        from /home/dmytro/.rvm/gems/ruby-2.1.2@mailcatcher/gems/activesupport-3.2.19/lib/active_support/core_ext.rb:1:in `<top (required)>'
        from /home/dmytro/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /home/dmytro/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /home/dmytro/.rvm/gems/ruby-2.1.2@mailcatcher/gems/mailcatcher-0.5.12/lib/mail_catcher.rb:1:in `<top (required)>'
        from /home/dmytro/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /home/dmytro/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /home/dmytro/.rvm/gems/ruby-2.1.2@mailcatcher/gems/mailcatcher-0.5.12/bin/mailcatcher:3:in `<top (required)>'
        from /home/dmytro/.rvm/gems/ruby-2.1.2@mailcatcher/bin/mailcatcher:23:in `load'
        from /home/dmytro/.rvm/gems/ruby-2.1.2@mailcatcher/bin/mailcatcher:23:in `<main>'
        from /home/dmytro/.rvm/gems/ruby-2.1.2@mailcatcher/bin/ruby_executable_hooks:15:in `eval'
        from /home/dmytro/.rvm/gems/ruby-2.1.2@mailcatcher/bin/ruby_executable_hooks:15:in `<main>'
```

What can be a problem? Thanks.

**Comment by sj26** [comment]
Please remove any prerelease versions of i18n to make this work. Mailcatcher works with the released version of i18n 0.7.0+
