### ISSUE TITLE
Undefined method decode if an attachment is added to an email

### ISSUE THREAD

**Issue by jaroslavtyc** [sj26/mailcatcher#180]
Hi, i met bellow error, which blocks me to use great Mailcatcher to catch email with an attachment.
A bit of Google digging reveals similar problem as a ruby 1.9 bug:
http://stackoverflow.com/questions/17854144/why-do-i-get-undefined-method-encoding

Error backtrace:
```
/var/lib/gems/1.9.1/gems/mail-2.6.3/lib/mail/body.rb:165:in `encoded': undefined method `decode' for nil:NilClass (NoMethodError)
        from /var/lib/gems/1.9.1/gems/mail-2.6.3/lib/mail/message.rb:1813:in `encoded'
        from /var/lib/gems/1.9.1/gems/mail-2.6.3/lib/mail/body.rb:153:in `block in encoded'
        from /var/lib/gems/1.9.1/gems/mail-2.6.3/lib/mail/parts_list.rb:11:in `block in collect'
        from /var/lib/gems/1.9.1/gems/mail-2.6.3/lib/mail/parts_list.rb:11:in `each'
        from /var/lib/gems/1.9.1/gems/mail-2.6.3/lib/mail/parts_list.rb:11:in `collect'
        from /var/lib/gems/1.9.1/gems/mail-2.6.3/lib/mail/body.rb:153:in `encoded'
        from /var/lib/gems/1.9.1/gems/mail-2.6.3/lib/mail/message.rb:1813:in `encoded'
        from /var/lib/gems/1.9.1/gems/mail-2.6.3/lib/mail/check_delivery_params.rb:12:in `check_delivery_params'
        from /var/lib/gems/1.9.1/gems/mail-2.6.3/lib/mail/network/delivery_methods/smtp.rb:98:in `deliver!'
        from /var/lib/gems/1.9.1/gems/mail-2.6.3/lib/mail/message.rb:2141:in `do_delivery'
        from /var/lib/gems/1.9.1/gems/mail-2.6.3/lib/mail/message.rb:238:in `deliver'
        from /var/lib/gems/1.9.1/gems/mailcatcher-0.5.12/bin/catchmail:50:in `<top (required)>'
        from /usr/local/bin/catchmail:23:in `load'
        from /usr/local/bin/catchmail:23:in `<main>'
```

**Comment by sj26** [comment]
Can you provide a full source message which produces this problem?

**Comment by sj26** [comment]
If you can supply a message which reproduces this problem please feel free to reopen the issue. :-)
