### ISSUE TITLE
Error : Did not recognize your adapter specification

### ISSUE THREAD

**Issue by SebSept** [sj26/mailcatcher#189]
```

~ » mailcatcher --smtp-port 2029 --http-port 1081 -f                                                                                                                                                  
Starting MailCatcher
==> smtp://127.0.0.1:2029
==> http://127.0.0.1:1081
==> SMTP: Received message from '<contact@yep.com>' (479 bytes)
/usr/local/share/ruby/site_ruby/rubygems/core_ext/kernel_require.rb:55:in `require': Did not recognize your adapter specification (cannot load such file -- json/ext/parser). (MultiJson::AdapterError)
	from /usr/local/share/ruby/site_ruby/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /home/seb/.gem/ruby/gems/json_pure-1.8.2/lib/json/ext.rb:13:in `<module:Ext>'
	from /home/seb/.gem/ruby/gems/json_pure-1.8.2/lib/json/ext.rb:12:in `<module:JSON>'
	from /home/seb/.gem/ruby/gems/json_pure-1.8.2/lib/json/ext.rb:9:in `<top (required)>'
	from /usr/local/share/ruby/site_ruby/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/share/ruby/site_ruby/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /home/seb/.gem/ruby/gems/multi_json-1.10.1/lib/multi_json/adapters/json_gem.rb:1:in `<top (required)>'
	from /usr/local/share/ruby/site_ruby/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/share/ruby/site_ruby/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /home/seb/.gem/ruby/gems/multi_json-1.10.1/lib/multi_json.rb:153:in `load_adapter_from_string_name'
	from /home/seb/.gem/ruby/gems/multi_json-1.10.1/lib/multi_json.rb:98:in `load_adapter'
	from /home/seb/.gem/ruby/gems/multi_json-1.10.1/lib/multi_json.rb:100:in `load_adapter'
	from /home/seb/.gem/ruby/gems/multi_json-1.10.1/lib/multi_json.rb:90:in `use'
	from /home/seb/.gem/ruby/gems/multi_json-1.10.1/lib/multi_json.rb:72:in `adapter'
	from /home/seb/.gem/ruby/gems/multi_json-1.10.1/lib/multi_json.rb:130:in `current_adapter'
	from /home/seb/.gem/ruby/gems/multi_json-1.10.1/lib/multi_json.rb:117:in `load'
	from /home/seb/.gem/ruby/gems/activesupport-3.2.21/lib/active_support/json/decoding.rb:15:in `decode'
	from /home/seb/.gem/ruby/gems/mailcatcher-0.5.12/lib/mail_catcher/mail.rb:84:in `block in message'
	from /home/seb/.gem/ruby/gems/mailcatcher-0.5.12/lib/mail_catcher/mail.rb:83:in `tap'
	from /home/seb/.gem/ruby/gems/mailcatcher-0.5.12/lib/mail_catcher/mail.rb:83:in `message'
	from /home/seb/.gem/ruby/gems/mailcatcher-0.5.12/lib/mail_catcher/mail.rb:56:in `block in add_message'
	from /home/seb/.gem/ruby/gems/eventmachine-1.0.4/lib/eventmachine.rb:968:in `call'
	from /home/seb/.gem/ruby/gems/eventmachine-1.0.4/lib/eventmachine.rb:968:in `block in run_deferred_callbacks'
	from /home/seb/.gem/ruby/gems/eventmachine-1.0.4/lib/eventmachine.rb:965:in `times'
	from /home/seb/.gem/ruby/gems/eventmachine-1.0.4/lib/eventmachine.rb:965:in `run_deferred_callbacks'
	from /home/seb/.gem/ruby/gems/eventmachine-1.0.4/lib/eventmachine.rb:187:in `run_machine'
	from /home/seb/.gem/ruby/gems/eventmachine-1.0.4/lib/eventmachine.rb:187:in `run'
	from /home/seb/.gem/ruby/gems/mailcatcher-0.5.12/lib/mail_catcher.rb:134:in `run!'
	from /home/seb/.gem/ruby/gems/mailcatcher-0.5.12/bin/mailcatcher:4:in `<top (required)>'
	from /usr/local/bin/mailcatcher:23:in `load'
	from /usr/local/bin/mailcatcher:23:in `<main>'

```

Any idea how to fix this ?

**Comment by sj26** [comment]
What version of ruby are you using? `ruby --version`

What OS/platform are you on?

Do you have the json gem? `gem list`

**Comment by SebSept** [comment]
Sorry for late answer (I'm on another computer)
I've added json gem, plus another json package added (I google about a previous error)
I'm on fedora 19.

(I'll give more nfo tomorrow)

**Comment by SebSept** [comment]
I switched to fedora 21 but did not tried mailcatcher.
I had to find an alternative solution to mailcatcher faster.
Maybe I'll retry another day ...

Thanks for your project, thanks for sharing.

**Comment by sj26** [comment]
No worries, sorry it didn't work for you.
