### ISSUE TITLE
utf-8 encoding of source

### ISSUE THREAD

**Issue by nanshu** [sj26/mailcatcher#201]
MailCatcher will crash when click on an email message including unicode characters. 

<code>
/var/lib/gems/1.9.1/gems/activesupport-4.2.0/lib/active_support/core_ext/object/json.rb:34:in `encode': "\xE2" from ASCII-8BIT to UTF-8 (Encoding::UndefinedConversionError)
</code>

Some debugging shows that MailCatcher stores the message source as BLOB data type in SQLITE3, while according to https://github.com/sparklemotion/sqlite3-ruby/blob/b73fae5a4c515cbe2bbcf2bb01be4f8edd86d4b8/ext/sqlite3/database.c line 284, BLOB data are  encoded to string using "rb_tainted_str_new", which creates string with ASCII-8BIT (BINARY) encoding. Therefore, the json encoder will get have an error when trying to encode unicode characters from ASCII-8BIT to UTF-8.

force_encode message["source"] using UTF-8 fixed the issue.

**Comment by drmikecrowe** [comment]
@nanshu -- I'm not a ruby programmer, can you explain how to fix it?

**Comment by nanshu** [comment]
@drmikecrowe I've forked this repository and implemented my fix there. I am not sure if the fix covers all the places that needs patch but you may try to see if it works for you. nanshu/mailcatcher

**Comment by eexit** [comment]
It looks like I have somewhat the same error here:

```
mailcatcher -vf
Starting MailCatcher
==> smtp://127.0.0.1:1025
==> http://0.0.0.0:1080
==> SMTP: Received message from '<noreply@foobar.com>' (15665 bytes)
/home/vagrant/.rvm/gems/ruby-2.2.0/gems/activesupport-4.2.0/lib/active_support/core_ext/object/json.rb:34:in `encode': "\xC2" from ASCII-8BIT to UTF-8 (Encoding::UndefinedConversionError)
	from /home/vagrant/.rvm/gems/ruby-2.2.0/gems/activesupport-4.2.0/lib/active_support/core_ext/object/json.rb:34:in `to_json'
	from /home/vagrant/.rvm/gems/ruby-2.2.0/gems/activesupport-4.2.0/lib/active_support/core_ext/object/json.rb:34:in `to_json_with_active_support_encoder'
	from /home/vagrant/.rvm/gems/ruby-2.2.0/gems/activesupport-4.2.0/lib/active_support/json/encoding.rb:56:in `to_json'
	from /home/vagrant/.rvm/gems/ruby-2.2.0/gems/json-1.8.2/lib/json/common.rb:223:in `generate'
	from /home/vagrant/.rvm/gems/ruby-2.2.0/gems/json-1.8.2/lib/json/common.rb:223:in `generate'
	from /home/vagrant/.rvm/gems/ruby-2.2.0/gems/activesupport-4.2.0/lib/active_support/json/encoding.rb:96:in `stringify'
	from /home/vagrant/.rvm/gems/ruby-2.2.0/gems/activesupport-4.2.0/lib/active_support/json/encoding.rb:34:in `encode'
	from /home/vagrant/.rvm/gems/ruby-2.2.0/gems/activesupport-4.2.0/lib/active_support/json/encoding.rb:21:in `encode'
	from /home/vagrant/.rvm/gems/ruby-2.2.0/gems/activesupport-4.2.0/lib/active_support/core_ext/object/json.rb:37:in `to_json_with_active_support_encoder'
	from /home/vagrant/.rvm/gems/ruby-2.2.0/gems/mailcatcher-0.6.1/lib/mail_catcher/web/application.rb:67:in `block (3 levels) in <class:Application>'
	from /home/vagrant/.rvm/gems/ruby-2.2.0/gems/eventmachine-1.0.4/lib/em/channel.rb:43:in `call'
	from /home/vagrant/.rvm/gems/ruby-2.2.0/gems/eventmachine-1.0.4/lib/em/channel.rb:43:in `block (3 levels) in push'
	from /home/vagrant/.rvm/gems/ruby-2.2.0/gems/eventmachine-1.0.4/lib/em/channel.rb:43:in `each'
	from /home/vagrant/.rvm/gems/ruby-2.2.0/gems/eventmachine-1.0.4/lib/em/channel.rb:43:in `block (2 levels) in push'
	from /home/vagrant/.rvm/gems/ruby-2.2.0/gems/eventmachine-1.0.4/lib/em/channel.rb:43:in `each'
	from /home/vagrant/.rvm/gems/ruby-2.2.0/gems/eventmachine-1.0.4/lib/em/channel.rb:43:in `block in push'
	from /home/vagrant/.rvm/gems/ruby-2.2.0/gems/eventmachine-1.0.4/lib/eventmachine.rb:248:in `call'
	from /home/vagrant/.rvm/gems/ruby-2.2.0/gems/eventmachine-1.0.4/lib/eventmachine.rb:248:in `schedule'
	from /home/vagrant/.rvm/gems/ruby-2.2.0/gems/eventmachine-1.0.4/lib/em/channel.rb:43:in `push'
	from /home/vagrant/.rvm/gems/ruby-2.2.0/gems/mailcatcher-0.6.1/lib/mail_catcher/mail.rb:57:in `block in add_message'
	from /home/vagrant/.rvm/gems/ruby-2.2.0/gems/eventmachine-1.0.4/lib/eventmachine.rb:968:in `call'
	from /home/vagrant/.rvm/gems/ruby-2.2.0/gems/eventmachine-1.0.4/lib/eventmachine.rb:968:in `block in run_deferred_callbacks'
	from /home/vagrant/.rvm/gems/ruby-2.2.0/gems/eventmachine-1.0.4/lib/eventmachine.rb:965:in `times'
	from /home/vagrant/.rvm/gems/ruby-2.2.0/gems/eventmachine-1.0.4/lib/eventmachine.rb:965:in `run_deferred_callbacks'
	from /home/vagrant/.rvm/gems/ruby-2.2.0/gems/eventmachine-1.0.4/lib/eventmachine.rb:187:in `run_machine'
	from /home/vagrant/.rvm/gems/ruby-2.2.0/gems/eventmachine-1.0.4/lib/eventmachine.rb:187:in `run'
	from /home/vagrant/.rvm/gems/ruby-2.2.0/gems/mailcatcher-0.6.1/lib/mail_catcher.rb:155:in `run!'
	from /home/vagrant/.rvm/gems/ruby-2.2.0/gems/mailcatcher-0.6.1/bin/mailcatcher:5:in `<top (required)>'
	from /home/vagrant/.rvm/gems/ruby-2.2.0/bin/mailcatcher:23:in `load'
	from /home/vagrant/.rvm/gems/ruby-2.2.0/bin/mailcatcher:23:in `<main>'
	from /home/vagrant/.rvm/gems/ruby-2.2.0/bin/ruby_executable_hooks:15:in `eval'
	from /home/vagrant/.rvm/gems/ruby-2.2.0/bin/ruby_executable_hooks:15:in `<main>'
zsh: exit 1     mailcatcher --http-ip=0.0.0.0 -vf
```

**Comment by dmromanov** [comment]
@eexit downgrading did not work

**Comment by simaks** [comment]
Downgrading to v0.5.12 worked, thanks

**Comment by issei-m** [comment]
I have same issue. also if downgraded to 0.5.*, it works.

**Comment by eexit** [comment]
@dmromanov did you also remove all dependencies?

By the way, the auto-refresh feature doesn't work when downgrading. I got this warning when launching mailcatcher:
```
mailcatcher
/home/vagrant/.rvm/gems/ruby-2.2.0/gems/activesupport-3.2.21/lib/active_support/values/time_zone.rb:270: warning: circular argument reference - now
Starting MailCatcher
==> smtp://127.0.0.1:1025
==> http://0.0.0.0:1080
*** MailCatcher runs as a daemon by default. Go to the web interface to quit.
```

**Comment by sj26** [comment]
Can you provide an example message triggering this problem?

SMTP only allows ASCII over the wire so mail messages as source should still be ASCII. Perhaps it is a strange title encoding or similar?

**Comment by TiMESPLiNTER** [comment]
Also troubles with random crahses with the following PHP-Code:

```php
<?php var_dump(mail('sas@metanet.ch', 'Hallöllele', 'Ey du Löli')) ?>
```
If you request this script often mailcatcher crashes with the following issue. Probably it's because of the `ö`s.

```
==> smtp://127.0.0.1:1025
==> http://127.0.0.1:1080
==> SMTP: Received message from '<sas@localhost.localhost>' (316 bytes)
/Library/Ruby/Gems/2.0.0/gems/activesupport-4.2.0/lib/active_support/core_ext/object/json.rb:34:in `encode': "\xC3" from ASCII-8BIT to UTF-8 (Encoding::UndefinedConversionError)
from /Library/Ruby/Gems/2.0.0/gems/activesupport-4.2.0/lib/active_support/core_ext/object/json.rb:34:in `to_json'
from /Library/Ruby/Gems/2.0.0/gems/activesupport-4.2.0/lib/active_support/core_ext/object/json.rb:34:in `to_json_with_active_support_encoder'
from /Library/Ruby/Gems/2.0.0/gems/activesupport-4.2.0/lib/active_support/json/encoding.rb:56:in `to_json'
from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/json/common.rb:224:in `generate'
from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/json/common.rb:224:in `generate'
from /Library/Ruby/Gems/2.0.0/gems/activesupport-4.2.0/lib/active_support/json/encoding.rb:96:in `stringify'
from /Library/Ruby/Gems/2.0.0/gems/activesupport-4.2.0/lib/active_support/json/encoding.rb:34:in `encode'
from /Library/Ruby/Gems/2.0.0/gems/activesupport-4.2.0/lib/active_support/json/encoding.rb:21:in `encode'
from /Library/Ruby/Gems/2.0.0/gems/activesupport-4.2.0/lib/active_support/core_ext/object/json.rb:37:in `to_json_with_active_support_encoder'
from /Library/Ruby/Gems/2.0.0/gems/mailcatcher-0.6.1/lib/mail_catcher/web/application.rb:67:in `block (3 levels) in <class:Application>'
from /Library/Ruby/Gems/2.0.0/gems/eventmachine-1.0.5/lib/em/channel.rb:43:in `call'
from /Library/Ruby/Gems/2.0.0/gems/eventmachine-1.0.5/lib/em/channel.rb:43:in `block (3 levels) in push'
from /Library/Ruby/Gems/2.0.0/gems/eventmachine-1.0.5/lib/em/channel.rb:43:in `each'
from /Library/Ruby/Gems/2.0.0/gems/eventmachine-1.0.5/lib/em/channel.rb:43:in `block (2 levels) in push'
from /Library/Ruby/Gems/2.0.0/gems/eventmachine-1.0.5/lib/em/channel.rb:43:in `each'
from /Library/Ruby/Gems/2.0.0/gems/eventmachine-1.0.5/lib/em/channel.rb:43:in `block in push'
from /Library/Ruby/Gems/2.0.0/gems/eventmachine-1.0.5/lib/eventmachine.rb:248:in `call'
from /Library/Ruby/Gems/2.0.0/gems/eventmachine-1.0.5/lib/eventmachine.rb:248:in `schedule'
from /Library/Ruby/Gems/2.0.0/gems/eventmachine-1.0.5/lib/em/channel.rb:43:in `push'
from /Library/Ruby/Gems/2.0.0/gems/mailcatcher-0.6.1/lib/mail_catcher/mail.rb:57:in `block in add_message'
from /Library/Ruby/Gems/2.0.0/gems/eventmachine-1.0.5/lib/eventmachine.rb:968:in `call'
from /Library/Ruby/Gems/2.0.0/gems/eventmachine-1.0.5/lib/eventmachine.rb:968:in `block in run_deferred_callbacks'
from /Library/Ruby/Gems/2.0.0/gems/eventmachine-1.0.5/lib/eventmachine.rb:965:in `times'
from /Library/Ruby/Gems/2.0.0/gems/eventmachine-1.0.5/lib/eventmachine.rb:965:in `run_deferred_callbacks'
from /Library/Ruby/Gems/2.0.0/gems/eventmachine-1.0.5/lib/eventmachine.rb:187:in `run_machine'
from /Library/Ruby/Gems/2.0.0/gems/eventmachine-1.0.5/lib/eventmachine.rb:187:in `run'
from /Library/Ruby/Gems/2.0.0/gems/mailcatcher-0.6.1/lib/mail_catcher.rb:155:in `run!'
from /Library/Ruby/Gems/2.0.0/gems/mailcatcher-0.6.1/bin/mailcatcher:5:in `<top (required)>'
from /usr/bin/mailcatcher:23:in `load'
from /usr/bin/mailcatcher:23:in `<main>'
```

**Comment by eexit** [comment]
@sj26 I don't send particular odd characters but there's obviously a regression.

**Comment by kusmierz** [comment]
0.5.12 works like a charm. I had problems with 0.6.1 and polish chars with diacritics (żółćęśąźń).

**Comment by marcosgdf** [comment]
Version: 0.6.1

Remote Address:192.168.42.101:1080
Request URL:http://dolibarr.local:1080/messages/1.json
Request Method:GET
Status Code:500 Internal Server Error
Response Headers
view source
Connection:keep-alive
Content-Length:30
Content-Type:text/html;charset=utf-8
Server:thin 1.5.1 codename Straight Razor
X-Content-Type-Options:nosniff
X-Frame-Options:SAMEORIGIN
X-XSS-Protection:1; mode=block
Request Headers
view source
Accept:application/json, text/javascript, */*; q=0.01
Accept-Encoding:gzip, deflate, sdch
Accept-Language:es-ES,es;q=0.8,en;q=0.6,gl;q=0.4
Connection:keep-alive
Cookie:DOLSESSID_2afec227796cda3b39c0f7714dbb561c=o7plgqhm5eqrnmb40ertrdi975; XDEBUG_SESSION=phpstorm
Host:dolibarr.local:1080
Referer:http://dolibarr.local:1080/
User-Agent:Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.76 Safari/537.36
X-Requested-With:XMLHttpRequest

```
Encoding::UndefinedConversionError - "\xC3" from ASCII-8BIT to UTF-8:
	/usr/local/rvm/gems/ruby-1.9.3-p551/gems/activesupport-4.2.0/lib/active_support/core_ext/object/json.rb:34:in `encode'
	/usr/local/rvm/gems/ruby-1.9.3-p551/gems/activesupport-4.2.0/lib/active_support/core_ext/object/json.rb:34:in `to_json'
	/usr/local/rvm/gems/ruby-1.9.3-p551/gems/activesupport-4.2.0/lib/active_support/core_ext/object/json.rb:34:in `to_json_with_active_support_encoder'
	/usr/local/rvm/gems/ruby-1.9.3-p551/gems/activesupport-4.2.0/lib/active_support/json/encoding.rb:56:in `to_json'
	/usr/local/rvm/gems/ruby-1.9.3-p551/gems/json-1.8.2/lib/json/common.rb:223:in `generate'
	/usr/local/rvm/gems/ruby-1.9.3-p551/gems/json-1.8.2/lib/json/common.rb:223:in `generate'
	/usr/local/rvm/gems/ruby-1.9.3-p551/gems/activesupport-4.2.0/lib/active_support/json/encoding.rb:96:in `stringify'
	/usr/local/rvm/gems/ruby-1.9.3-p551/gems/activesupport-4.2.0/lib/active_support/json/encoding.rb:34:in `encode'
	/usr/local/rvm/gems/ruby-1.9.3-p551/gems/activesupport-4.2.0/lib/active_support/json/encoding.rb:21:in `encode'
	/usr/local/rvm/gems/ruby-1.9.3-p551/gems/activesupport-4.2.0/lib/active_support/core_ext/object/json.rb:37:in `to_json_with_active_support_encoder'
	/usr/local/rvm/gems/ruby-1.9.3-p551/gems/mailcatcher-0.6.1/lib/mail_catcher/web/application.rb:87:in `block in <class:Application>'
	/usr/local/rvm/gems/ruby-1.9.3-p551/gems/sinatra-1.4.5/lib/sinatra/base.rb:1603:in `call'
	/usr/local/rvm/gems/ruby-1.9.3-p551/gems/sinatra-1.4.5/lib/sinatra/base.rb:1603:in `block in compile!'
	/usr/local/rvm/gems/ruby-1.9.3-p551/gems/sinatra-1.4.5/lib/sinatra/base.rb:966:in `[]'
	/usr/local/rvm/gems/ruby-1.9.3-p551/gems/sinatra-1.4.5/lib/sinatra/base.rb:966:in `block (3 levels) in route!'
	/usr/local/rvm/gems/ruby-1.9.3-p551/gems/sinatra-1.4.5/lib/sinatra/base.rb:985:in `route_eval'
	/usr/local/rvm/gems/ruby-1.9.3-p551/gems/sinatra-1.4.5/lib/sinatra/base.rb:966:in `block (2 levels) in route!'
	/usr/local/rvm/gems/ruby-1.9.3-p551/gems/sinatra-1.4.5/lib/sinatra/base.rb:1006:in `block in process_route'
	/usr/local/rvm/gems/ruby-1.9.3-p551/gems/sinatra-1.4.5/lib/sinatra/base.rb:1004:in `catch'
	/usr/local/rvm/gems/ruby-1.9.3-p551/gems/sinatra-1.4.5/lib/sinatra/base.rb:1004:in `process_route'
	/usr/local/rvm/gems/ruby-1.9.3-p551/gems/sinatra-1.4.5/lib/sinatra/base.rb:964:in `block in route!'
	/usr/local/rvm/gems/ruby-1.9.3-p551/gems/sinatra-1.4.5/lib/sinatra/base.rb:963:in `each'
	/usr/local/rvm/gems/ruby-1.9.3-p551/gems/sinatra-1.4.5/lib/sinatra/base.rb:963:in `route!'
	/usr/local/rvm/gems/ruby-1.9.3-p551/gems/sinatra-1.4.5/lib/sinatra/base.rb:1076:in `block in dispatch!'
	/usr/local/rvm/gems/ruby-1.9.3-p551/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `block in invoke'
	/usr/local/rvm/gems/ruby-1.9.3-p551/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `catch'
	/usr/local/rvm/gems/ruby-1.9.3-p551/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `invoke'
	/usr/local/rvm/gems/ruby-1.9.3-p551/gems/sinatra-1.4.5/lib/sinatra/base.rb:1073:in `dispatch!'
	/usr/local/rvm/gems/ruby-1.9.3-p551/gems/sinatra-1.4.5/lib/sinatra/base.rb:898:in `block in call!'
	/usr/local/rvm/gems/ruby-1.9.3-p551/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `block in invoke'
	/usr/local/rvm/gems/ruby-1.9.3-p551/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `catch'
	/usr/local/rvm/gems/ruby-1.9.3-p551/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `invoke'
	/usr/local/rvm/gems/ruby-1.9.3-p551/gems/sinatra-1.4.5/lib/sinatra/base.rb:898:in `call!'
	/usr/local/rvm/gems/ruby-1.9.3-p551/gems/sinatra-1.4.5/lib/sinatra/base.rb:886:in `call'
	/usr/local/rvm/gems/ruby-1.9.3-p551/gems/rack-protection-1.5.3/lib/rack/protection/xss_header.rb:18:in `call'
	/usr/local/rvm/gems/ruby-1.9.3-p551/gems/rack-protection-1.5.3/lib/rack/protection/path_traversal.rb:16:in `call'
	/usr/local/rvm/gems/ruby-1.9.3-p551/gems/rack-protection-1.5.3/lib/rack/protection/json_csrf.rb:18:in `call'
	/usr/local/rvm/gems/ruby-1.9.3-p551/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
	/usr/local/rvm/gems/ruby-1.9.3-p551/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
	/usr/local/rvm/gems/ruby-1.9.3-p551/gems/rack-protection-1.5.3/lib/rack/protection/frame_options.rb:31:in `call'
	/usr/local/rvm/gems/ruby-1.9.3-p551/gems/rack-1.6.0/lib/rack/nulllogger.rb:9:in `call'
	/usr/local/rvm/gems/ruby-1.9.3-p551/gems/rack-1.6.0/lib/rack/head.rb:13:in `call'
	/usr/local/rvm/gems/ruby-1.9.3-p551/gems/sinatra-1.4.5/lib/sinatra/base.rb:180:in `call'
	/usr/local/rvm/gems/ruby-1.9.3-p551/gems/sinatra-1.4.5/lib/sinatra/base.rb:2014:in `call'
	/usr/local/rvm/gems/ruby-1.9.3-p551/gems/sinatra-1.4.5/lib/sinatra/base.rb:1478:in `block in call'
	/usr/local/rvm/gems/ruby-1.9.3-p551/gems/sinatra-1.4.5/lib/sinatra/base.rb:1788:in `synchronize'
	/usr/local/rvm/gems/ruby-1.9.3-p551/gems/sinatra-1.4.5/lib/sinatra/base.rb:1478:in `call'
	/usr/local/rvm/gems/ruby-1.9.3-p551/gems/rack-1.6.0/lib/rack/urlmap.rb:66:in `block in call'
	/usr/local/rvm/gems/ruby-1.9.3-p551/gems/rack-1.6.0/lib/rack/urlmap.rb:50:in `each'
	/usr/local/rvm/gems/ruby-1.9.3-p551/gems/rack-1.6.0/lib/rack/urlmap.rb:50:in `call'
	/usr/local/rvm/gems/ruby-1.9.3-p551/gems/rack-1.6.0/lib/rack/builder.rb:153:in `call'
	/usr/local/rvm/gems/ruby-1.9.3-p551/gems/mailcatcher-0.6.1/lib/mail_catcher/web.rb:19:in `call'
	/usr/local/rvm/gems/ruby-1.9.3-p551/gems/thin-1.5.1/lib/thin/connection.rb:81:in `block in pre_process'
	/usr/local/rvm/gems/ruby-1.9.3-p551/gems/thin-1.5.1/lib/thin/connection.rb:79:in `catch'
	/usr/local/rvm/gems/ruby-1.9.3-p551/gems/thin-1.5.1/lib/thin/connection.rb:79:in `pre_process'
	/usr/local/rvm/gems/ruby-1.9.3-p551/gems/thin-1.5.1/lib/thin/connection.rb:54:in `process'
	/usr/local/rvm/gems/ruby-1.9.3-p551/gems/thin-1.5.1/lib/thin/connection.rb:39:in `receive_data'
	/usr/local/rvm/gems/ruby-1.9.3-p551/gems/eventmachine-1.0.5/lib/eventmachine.rb:187:in `run_machine'
	/usr/local/rvm/gems/ruby-1.9.3-p551/gems/eventmachine-1.0.5/lib/eventmachine.rb:187:in `run'
	/usr/local/rvm/gems/ruby-1.9.3-p551/gems/mailcatcher-0.6.1/lib/mail_catcher.rb:155:in `run!'
	/usr/local/rvm/gems/ruby-1.9.3-p551/gems/mailcatcher-0.6.1/bin/mailcatcher:5:in `<top (required)>'
	/usr/local/rvm/gems/ruby-1.9.3-p551/bin/mailcatcher:23:in `load'
	/usr/local/rvm/gems/ruby-1.9.3-p551/bin/mailcatcher:23:in `<main>'
	/usr/local/rvm/gems/ruby-1.9.3-p551/bin/ruby_executable_hooks:15:in `eval'
	/usr/local/rvm/gems/ruby-1.9.3-p551/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by fero8** [comment]
Same problem with 0.6.1 even without any special characters.

```
==> SMTP: Received message from '<test@example.com>' (2654 bytes)
/Library/Ruby/Gems/2.0.0/gems/activesupport-4.2.1/lib/active_support/core_ext/object/json.rb:34:in `encode': "\xC5" from ASCII-8BIT to UTF-8 (Encoding::UndefinedConversionError)
	from /Library/Ruby/Gems/2.0.0/gems/activesupport-4.2.1/lib/active_support/core_ext/object/json.rb:34:in `to_json'
	from /Library/Ruby/Gems/2.0.0/gems/activesupport-4.2.1/lib/active_support/core_ext/object/json.rb:34:in `to_json_with_active_support_encoder'
	from /Library/Ruby/Gems/2.0.0/gems/activesupport-4.2.1/lib/active_support/json/encoding.rb:56:in `to_json'
	from /Library/Ruby/Gems/2.0.0/gems/json-1.8.2/lib/json/common.rb:223:in `generate'
	from /Library/Ruby/Gems/2.0.0/gems/json-1.8.2/lib/json/common.rb:223:in `generate'
	from /Library/Ruby/Gems/2.0.0/gems/activesupport-4.2.1/lib/active_support/json/encoding.rb:96:in `stringify'
	from /Library/Ruby/Gems/2.0.0/gems/activesupport-4.2.1/lib/active_support/json/encoding.rb:34:in `encode'
	from /Library/Ruby/Gems/2.0.0/gems/activesupport-4.2.1/lib/active_support/json/encoding.rb:21:in `encode'
	from /Library/Ruby/Gems/2.0.0/gems/activesupport-4.2.1/lib/active_support/core_ext/object/json.rb:37:in `to_json_with_active_support_encoder'
	from /Library/Ruby/Gems/2.0.0/gems/mailcatcher-0.6.1/lib/mail_catcher/web/application.rb:67:in `block (3 levels) in <class:Application>'
	from /Library/Ruby/Gems/2.0.0/gems/eventmachine-1.0.3/lib/em/channel.rb:43:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/eventmachine-1.0.3/lib/em/channel.rb:43:in `block (3 levels) in push'
	from /Library/Ruby/Gems/2.0.0/gems/eventmachine-1.0.3/lib/em/channel.rb:43:in `each'
	from /Library/Ruby/Gems/2.0.0/gems/eventmachine-1.0.3/lib/em/channel.rb:43:in `block (2 levels) in push'
	from /Library/Ruby/Gems/2.0.0/gems/eventmachine-1.0.3/lib/em/channel.rb:43:in `each'
	from /Library/Ruby/Gems/2.0.0/gems/eventmachine-1.0.3/lib/em/channel.rb:43:in `block in push'
	from /Library/Ruby/Gems/2.0.0/gems/eventmachine-1.0.3/lib/eventmachine.rb:248:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/eventmachine-1.0.3/lib/eventmachine.rb:248:in `schedule'
	from /Library/Ruby/Gems/2.0.0/gems/eventmachine-1.0.3/lib/em/channel.rb:43:in `push'
	from /Library/Ruby/Gems/2.0.0/gems/mailcatcher-0.6.1/lib/mail_catcher/mail.rb:57:in `block in add_message'
	from /Library/Ruby/Gems/2.0.0/gems/eventmachine-1.0.3/lib/eventmachine.rb:959:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/eventmachine-1.0.3/lib/eventmachine.rb:959:in `block in run_deferred_callbacks'
	from /Library/Ruby/Gems/2.0.0/gems/eventmachine-1.0.3/lib/eventmachine.rb:956:in `times'
	from /Library/Ruby/Gems/2.0.0/gems/eventmachine-1.0.3/lib/eventmachine.rb:956:in `run_deferred_callbacks'
	from /Library/Ruby/Gems/2.0.0/gems/eventmachine-1.0.3/lib/eventmachine.rb:187:in `run_machine'
	from /Library/Ruby/Gems/2.0.0/gems/eventmachine-1.0.3/lib/eventmachine.rb:187:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/mailcatcher-0.6.1/lib/mail_catcher.rb:155:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/mailcatcher-0.6.1/bin/mailcatcher:5:in `<top (required)>'
	from /usr/bin/mailcatcher:23:in `load'
	from /usr/bin/mailcatcher:23:in `<main>'```

**Comment by ollietreend** [comment]
:thumbsup: +1 - experiencing the same issues using mailcatcher with UTF-8 encoded emails.

**Comment by DmitriyS** [comment]
Confirm this issue with v 0.6.1

**Comment by nilsglow** [comment]
I also confirm issue with 0.6.1, whereas it works with 0.5.12

**Comment by npanasenko** [comment]
Confirming this issues as well with v 0.6.1

**Comment by newcron** [comment]
same here. it seems to be unable to handle utf-8 encoded e-mails.

**Comment by entr** [comment]
same for me 0.6.1

**Comment by ollietreend** [comment]
Until this bug is resolved I'm getting good results with the free package from [Mailtrap.io](https://mailtrap.io). It's working nicely. The only annoyance so far is the 2 messages per second limit which only really becomes a problem when testing batch email scripts.

**Comment by eexit** [comment]
@ollietreend or you can downgrade to 0.5.12 :)

**Comment by entr** [comment]
Downgrading to 0.5.12 confirmed to work so far.

**Comment by ollietreend** [comment]
@eexit Oh! I didn't realise that. Would you mind explaining how to downgrade it? Unfortunately I'm not too experienced with the ruby gems package manager.

**Comment by arnov** [comment]
gem install mailcatcher -v 0.5.12

**Comment by ollietreend** [comment]
@arnov That was easier than expected.. thanks!

**Comment by zeroedin** [comment]
Running into this issue as well.

**Comment by plista-mp** [comment]
different user - same problem, 0.5.12 works great

**Comment by t0xicCode** [comment]
I updated activesupport to 4.2.3 and json to 1.8.3, and I wasn't able to reproduce the error any more.

**Comment by cybafelo** [comment]
I have same problem - cannot use 0.5.12 because it does not send an announcement.
The announce string for mailcatcher is: "220 EventMachine SMTP Server"
For other mail servers is something like "220 ***********************" and so on.

0.5.12 does not produce this - causes phpmailer to wait timeout value before continuing - which creates a huge lag in my unit tests (between 10 and 300 seconds depending on phpmailer versions and defaults)

0.6.1 does produce this announcement, but, fails sending UTF-8 mails. So - now I'm really stuck and  what do we do? Get rid of mailcatcher alltogether?

**Comment by arunkumarg** [comment]
Thanks alot.  0.5.12 working great.

**Comment by Erwane** [comment]
Update gem json to 1.8.3 works fine

**Comment by Stex** [comment]
Using the [activesupport-json_encoder](https://github.com/rails/activesupport-json_encoder) gem seems to fix these problems. It breaks the test cases though.

If someone wants to try it, add the following lines to the specified files:

```ruby
# mailcatcher.gemspec
s.add_dependency 'activesupport-json_encoder', '~> 1.1.0'

# lib/mail_catcher/mail_catcher.rb
require 'activesupport/json_encoder'
```

**Comment by Erwane** [comment]
This solution is working fine ;)
Patch or create a pull-request ?

**Comment by numediaweb** [comment]
I created a (blog post) [http://www.numediaweb.com/installing-mailcatcher-in-windows/1290]about this.

**Comment by eexit** [comment]
Problem is that this tool looks to be not maintained anymore... :(

**Comment by sj26** [comment]
I'll happily accept a patch with test cases. The problem here is incompatibility arising from particular gem versions which is difficult to solve.

**Comment by Erwane** [comment]
you can't define a min an max versions of dependencies ? like in composer ?

**Comment by sj26** [comment]
Please try v0.6.5 and create a new issue with a fresh backtrace and breaking source message if you continue having issues.
