### ISSUE TITLE
Internal Server Error when viewing a message

### ISSUE THREAD

**Issue by marcosgdf** [sj26/mailcatcher#214]
Version: 0.6.1

Remote Address:192.168.42.101:1080
Request URL:http://dolibarr.local:1080/messages/1.json
Request Method:GET
Status Code:500 Internal Server Error
Response Headers
view source
Connection:keep-alive
Content-Length:30
Content-Type:text/html;charset=utf-8
Server:thin 1.5.1 codename Straight Razor
X-Content-Type-Options:nosniff
X-Frame-Options:SAMEORIGIN
X-XSS-Protection:1; mode=block
Request Headers
view source
Accept:application/json, text/javascript, */*; q=0.01
Accept-Encoding:gzip, deflate, sdch
Accept-Language:es-ES,es;q=0.8,en;q=0.6,gl;q=0.4
Connection:keep-alive
Cookie:DOLSESSID_2afec227796cda3b39c0f7714dbb561c=o7plgqhm5eqrnmb40ertrdi975; XDEBUG_SESSION=phpstorm
Host:dolibarr.local:1080
Referer:http://dolibarr.local:1080/
User-Agent:Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.76 Safari/537.36
X-Requested-With:XMLHttpRequest

```
Encoding::UndefinedConversionError - "\xC3" from ASCII-8BIT to UTF-8:
	/usr/local/rvm/gems/ruby-1.9.3-p551/gems/activesupport-4.2.0/lib/active_support/core_ext/object/json.rb:34:in `encode'
	/usr/local/rvm/gems/ruby-1.9.3-p551/gems/activesupport-4.2.0/lib/active_support/core_ext/object/json.rb:34:in `to_json'
	/usr/local/rvm/gems/ruby-1.9.3-p551/gems/activesupport-4.2.0/lib/active_support/core_ext/object/json.rb:34:in `to_json_with_active_support_encoder'
	/usr/local/rvm/gems/ruby-1.9.3-p551/gems/activesupport-4.2.0/lib/active_support/json/encoding.rb:56:in `to_json'
	/usr/local/rvm/gems/ruby-1.9.3-p551/gems/json-1.8.2/lib/json/common.rb:223:in `generate'
	/usr/local/rvm/gems/ruby-1.9.3-p551/gems/json-1.8.2/lib/json/common.rb:223:in `generate'
	/usr/local/rvm/gems/ruby-1.9.3-p551/gems/activesupport-4.2.0/lib/active_support/json/encoding.rb:96:in `stringify'
	/usr/local/rvm/gems/ruby-1.9.3-p551/gems/activesupport-4.2.0/lib/active_support/json/encoding.rb:34:in `encode'
	/usr/local/rvm/gems/ruby-1.9.3-p551/gems/activesupport-4.2.0/lib/active_support/json/encoding.rb:21:in `encode'
	/usr/local/rvm/gems/ruby-1.9.3-p551/gems/activesupport-4.2.0/lib/active_support/core_ext/object/json.rb:37:in `to_json_with_active_support_encoder'
	/usr/local/rvm/gems/ruby-1.9.3-p551/gems/mailcatcher-0.6.1/lib/mail_catcher/web/application.rb:87:in `block in <class:Application>'
	/usr/local/rvm/gems/ruby-1.9.3-p551/gems/sinatra-1.4.5/lib/sinatra/base.rb:1603:in `call'
	/usr/local/rvm/gems/ruby-1.9.3-p551/gems/sinatra-1.4.5/lib/sinatra/base.rb:1603:in `block in compile!'
	/usr/local/rvm/gems/ruby-1.9.3-p551/gems/sinatra-1.4.5/lib/sinatra/base.rb:966:in `[]'
	/usr/local/rvm/gems/ruby-1.9.3-p551/gems/sinatra-1.4.5/lib/sinatra/base.rb:966:in `block (3 levels) in route!'
	/usr/local/rvm/gems/ruby-1.9.3-p551/gems/sinatra-1.4.5/lib/sinatra/base.rb:985:in `route_eval'
	/usr/local/rvm/gems/ruby-1.9.3-p551/gems/sinatra-1.4.5/lib/sinatra/base.rb:966:in `block (2 levels) in route!'
	/usr/local/rvm/gems/ruby-1.9.3-p551/gems/sinatra-1.4.5/lib/sinatra/base.rb:1006:in `block in process_route'
	/usr/local/rvm/gems/ruby-1.9.3-p551/gems/sinatra-1.4.5/lib/sinatra/base.rb:1004:in `catch'
	/usr/local/rvm/gems/ruby-1.9.3-p551/gems/sinatra-1.4.5/lib/sinatra/base.rb:1004:in `process_route'
	/usr/local/rvm/gems/ruby-1.9.3-p551/gems/sinatra-1.4.5/lib/sinatra/base.rb:964:in `block in route!'
	/usr/local/rvm/gems/ruby-1.9.3-p551/gems/sinatra-1.4.5/lib/sinatra/base.rb:963:in `each'
	/usr/local/rvm/gems/ruby-1.9.3-p551/gems/sinatra-1.4.5/lib/sinatra/base.rb:963:in `route!'
	/usr/local/rvm/gems/ruby-1.9.3-p551/gems/sinatra-1.4.5/lib/sinatra/base.rb:1076:in `block in dispatch!'
	/usr/local/rvm/gems/ruby-1.9.3-p551/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `block in invoke'
	/usr/local/rvm/gems/ruby-1.9.3-p551/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `catch'
	/usr/local/rvm/gems/ruby-1.9.3-p551/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `invoke'
	/usr/local/rvm/gems/ruby-1.9.3-p551/gems/sinatra-1.4.5/lib/sinatra/base.rb:1073:in `dispatch!'
	/usr/local/rvm/gems/ruby-1.9.3-p551/gems/sinatra-1.4.5/lib/sinatra/base.rb:898:in `block in call!'
	/usr/local/rvm/gems/ruby-1.9.3-p551/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `block in invoke'
	/usr/local/rvm/gems/ruby-1.9.3-p551/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `catch'
	/usr/local/rvm/gems/ruby-1.9.3-p551/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `invoke'
	/usr/local/rvm/gems/ruby-1.9.3-p551/gems/sinatra-1.4.5/lib/sinatra/base.rb:898:in `call!'
	/usr/local/rvm/gems/ruby-1.9.3-p551/gems/sinatra-1.4.5/lib/sinatra/base.rb:886:in `call'
	/usr/local/rvm/gems/ruby-1.9.3-p551/gems/rack-protection-1.5.3/lib/rack/protection/xss_header.rb:18:in `call'
	/usr/local/rvm/gems/ruby-1.9.3-p551/gems/rack-protection-1.5.3/lib/rack/protection/path_traversal.rb:16:in `call'
	/usr/local/rvm/gems/ruby-1.9.3-p551/gems/rack-protection-1.5.3/lib/rack/protection/json_csrf.rb:18:in `call'
	/usr/local/rvm/gems/ruby-1.9.3-p551/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
	/usr/local/rvm/gems/ruby-1.9.3-p551/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
	/usr/local/rvm/gems/ruby-1.9.3-p551/gems/rack-protection-1.5.3/lib/rack/protection/frame_options.rb:31:in `call'
	/usr/local/rvm/gems/ruby-1.9.3-p551/gems/rack-1.6.0/lib/rack/nulllogger.rb:9:in `call'
	/usr/local/rvm/gems/ruby-1.9.3-p551/gems/rack-1.6.0/lib/rack/head.rb:13:in `call'
	/usr/local/rvm/gems/ruby-1.9.3-p551/gems/sinatra-1.4.5/lib/sinatra/base.rb:180:in `call'
	/usr/local/rvm/gems/ruby-1.9.3-p551/gems/sinatra-1.4.5/lib/sinatra/base.rb:2014:in `call'
	/usr/local/rvm/gems/ruby-1.9.3-p551/gems/sinatra-1.4.5/lib/sinatra/base.rb:1478:in `block in call'
	/usr/local/rvm/gems/ruby-1.9.3-p551/gems/sinatra-1.4.5/lib/sinatra/base.rb:1788:in `synchronize'
	/usr/local/rvm/gems/ruby-1.9.3-p551/gems/sinatra-1.4.5/lib/sinatra/base.rb:1478:in `call'
	/usr/local/rvm/gems/ruby-1.9.3-p551/gems/rack-1.6.0/lib/rack/urlmap.rb:66:in `block in call'
	/usr/local/rvm/gems/ruby-1.9.3-p551/gems/rack-1.6.0/lib/rack/urlmap.rb:50:in `each'
	/usr/local/rvm/gems/ruby-1.9.3-p551/gems/rack-1.6.0/lib/rack/urlmap.rb:50:in `call'
	/usr/local/rvm/gems/ruby-1.9.3-p551/gems/rack-1.6.0/lib/rack/builder.rb:153:in `call'
	/usr/local/rvm/gems/ruby-1.9.3-p551/gems/mailcatcher-0.6.1/lib/mail_catcher/web.rb:19:in `call'
	/usr/local/rvm/gems/ruby-1.9.3-p551/gems/thin-1.5.1/lib/thin/connection.rb:81:in `block in pre_process'
	/usr/local/rvm/gems/ruby-1.9.3-p551/gems/thin-1.5.1/lib/thin/connection.rb:79:in `catch'
	/usr/local/rvm/gems/ruby-1.9.3-p551/gems/thin-1.5.1/lib/thin/connection.rb:79:in `pre_process'
	/usr/local/rvm/gems/ruby-1.9.3-p551/gems/thin-1.5.1/lib/thin/connection.rb:54:in `process'
	/usr/local/rvm/gems/ruby-1.9.3-p551/gems/thin-1.5.1/lib/thin/connection.rb:39:in `receive_data'
	/usr/local/rvm/gems/ruby-1.9.3-p551/gems/eventmachine-1.0.5/lib/eventmachine.rb:187:in `run_machine'
	/usr/local/rvm/gems/ruby-1.9.3-p551/gems/eventmachine-1.0.5/lib/eventmachine.rb:187:in `run'
	/usr/local/rvm/gems/ruby-1.9.3-p551/gems/mailcatcher-0.6.1/lib/mail_catcher.rb:155:in `run!'
	/usr/local/rvm/gems/ruby-1.9.3-p551/gems/mailcatcher-0.6.1/bin/mailcatcher:5:in `<top (required)>'
	/usr/local/rvm/gems/ruby-1.9.3-p551/bin/mailcatcher:23:in `load'
	/usr/local/rvm/gems/ruby-1.9.3-p551/bin/mailcatcher:23:in `<main>'
	/usr/local/rvm/gems/ruby-1.9.3-p551/bin/ruby_executable_hooks:15:in `eval'
	/usr/local/rvm/gems/ruby-1.9.3-p551/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by marcosgdf** [comment]
Duplicated of #201
