### ISSUE TITLE
version OPENSSL_1.0.0 not defined in file libcrypto.so.1.0.0 with link time reference

### ISSUE THREAD

**Issue by Naahuel** [sj26/mailcatcher#230]
Perhaps this is an issue with my system, but I can't find a way to fix this anywhere.

This is the error log of XAMPP, whenever I try to use mail() on PHP (the function returns `false` meaning the mail was not accepted by the SMPT server.

```
/usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require': /usr/lib/x86_64-linux-gnu/ruby/2.1.0/digest/md5.so: symbol MD5_Init, version OPENSSL_1.0.0 not defined in file libcrypto.so.1.0.0 with link time reference - /usr/lib/x86_64-linux-gnu/ruby/2.1.0/digest/md5.so (LoadError)
    from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /usr/lib/ruby/2.1.0/net/smtp.rb:23:in `<top (required)>'
    from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /var/lib/gems/2.1.0/gems/mail-2.6.3/lib/mail.rb:8:in `<module:Mail>'
    from /var/lib/gems/2.1.0/gems/mail-2.6.3/lib/mail.rb:2:in `<top (required)>'
    from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /var/lib/gems/2.1.0/gems/mailcatcher-0.6.1/bin/catchmail:7:in `rescue in <top (required)>'
    from /var/lib/gems/2.1.0/gems/mailcatcher-0.6.1/bin/catchmail:3:in `<top (required)>'
    from /usr/local/bin/catchmail:23:in `load'
    from /usr/local/bin/catchmail:23:in `<main>'
```

**Comment by sj26** [comment]
Sorry, this is an error with your ruby/openssl install. Make sure `ruby -r digest/md5 -r openssl -e "puts OpenSSL::VERSION"` works on your system before trying MailCatcher. Re-open if the problem persists once openssl is working.
