### ISSUE TITLE
Issue running with eventmachine 1.0.7 :   undefined method `close' for 13:Fixnum (NoMethodError)

### ISSUE THREAD

**Issue by bogdanRada** [sj26/mailcatcher#234]
Here is the backtrace: 

gems/eventmachine-1.0.7/lib/eventmachine.rb:1463:in `event_callback': undefined method `close' for 13:Fixnum (NoMethodError)
gems/eventmachine-1.0.7/lib/eventmachine.rb:187:in `run_machine'
gems/eventmachine-1.0.7/lib/eventmachine.rb:187:in `run'
gems/mailcatcher-0.2.4/lib/mail_catcher.rb:21:in `run'
gems/mailcatcher-0.2.4/bin/mailcatcher:44:in `<top (required)>'
	
Is there any way to fix this? Thank you.

**Comment by bogdanRada** [comment]
nevermind. Seems my version was outdated.
