### ISSUE TITLE
Crash on receiving mail: stack level too deep (SystemStackError)

### ISSUE THREAD

**Issue by kfnic** [sj26/mailcatcher#245]
The server starts up fine and is accessible via the web. The server stays running until an email is received / a connection is made, at which point it crashes as shown below.

I can reproduce this on demand by restarting an exim4 email server, which immediately crashes the mailcatcher instance it is configured to send to.

This error is appearing on two servers, both Ubuntu 12.04.2 LTS. The first has been tried with multiple version of Ruby, including ruby 2.2.3p173. The second server is using ruby 1.9.3p0.

An example error is included below:
```
    Starting MailCatcher
    ==> smtp://ip_address:2525
    ==> http://127.0.0.1:1099
    /home/user/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/eventmachine-1.0.5/lib/em/protocols/smtpserver.rb:551:in `process_data_line': stack level too deep (SystemStackError)
    	from /home/user/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/eventmachine-1.0.5/lib/em/protocols/smtpserver.rb:196:in `receive_line'
    	from /home/user/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/eventmachine-1.0.5/lib/em/protocols/linetext2.rb:64:in `receive_data'
    	from /home/user/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/eventmachine-1.0.5/lib/em/protocols/linetext2.rb:65:in `receive_data'
    	from /home/user/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/eventmachine-1.0.5/lib/em/protocols/linetext2.rb:65:in `receive_data'
    	from /home/user/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/eventmachine-1.0.5/lib/em/protocols/linetext2.rb:65:in `receive_data'
    	from /home/user/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/eventmachine-1.0.5/lib/em/protocols/linetext2.rb:65:in `receive_data'
    	from /home/user/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/eventmachine-1.0.5/lib/em/protocols/linetext2.rb:65:in `receive_data'
    	from /home/user/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/eventmachine-1.0.5/lib/em/protocols/linetext2.rb:65:in `receive_data'
    	 ... 6886 levels...
    	from /home/user/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/mailcatcher-0.6.1/lib/mail_catcher.rb:155:in `run!'
    	from /home/user/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/mailcatcher-0.6.1/bin/mailcatcher:5:in `<top (required)>'
    	from /home/user/.rbenv/versions/2.2.3/bin/mailcatcher:23:in `load'
    	from /home/user/.rbenv/versions/2.2.3/bin/mailcatcher:23:in `<main>'

```

**Comment by sj26** [comment]
Please upgrade to 0.6.2.
