### ISSUE TITLE
Win10: Out of memory

### ISSUE THREAD

**Issue by Bushstar** [sj26/mailcatcher#248]
Running mailcatcher on Windows 10 64-bit. I have Ruby 2.2.3pre173, installed with RubyInstaller and also have the DevKit. If I leave mailcatcher running it is only a matter of time before it throws the error below and crashes. Ideally mailcatcher would run non-stop but I have to keep starting it up after it crashes.
```
mailcatcher -b
Starting MailCatcher
==> smtp://127.0.0.1:1025
==> http://127.0.0.1:1080
C:/Ruby22/lib/ruby/gems/2.2.0/gems/eventmachine-1.0.5/lib/eventmachine.rb:187:in `run_machine': failed to allocate memory (NoMemoryError)
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/eventmachine-1.0.5/lib/eventmachine.rb:187:in `run'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/mailcatcher-0.6.1/lib/mail_catcher.rb:155:in `run!'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/mailcatcher-0.6.1/bin/mailcatcher:5:in `<top (required)>'
        from C:/Ruby22/bin/mailcatcher:23:in `load'
        from C:/Ruby22/bin/mailcatcher:23:in `<main>'
```

**Comment by CloCkWeRX** [comment]
#210

**Comment by sj26** [comment]
See #210, and please try version 0.6.2.
