### ISSUE TITLE
Cannot start mailcatcher

### ISSUE THREAD

**Issue by abrambailey** [sj26/mailcatcher#257]
```ruby
➜  git:(qa) ✗ mailcatcher
/Users/x/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/specification.rb:2157:in `method_missing': undefined method `this' for #<Gem::Specification:0x3fd1b54c07f4 mailcatcher-0.6.2> (NoMethodError)
	from /Users/x/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/specification.rb:1056:in `find_active_stub_by_path'
	from /Users/x/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:63:in `require'
	from /Users/x/.rvm/gems/ruby-2.2.1@hearingtracker/gems/mailcatcher-0.6.2/bin/mailcatcher:3:in `<top (required)>'
	from /Users/x/.rvm/gems/ruby-2.2.1@hearingtracker/bin/mailcatcher:23:in `load'
	from /Users/x/.rvm/gems/ruby-2.2.1@hearingtracker/bin/mailcatcher:23:in `<main>'
	from /Users/x/.rvm/gems/ruby-2.2.1@hearingtracker/bin/ruby_executable_hooks:15:in `eval'
	from /Users/x/.rvm/gems/ruby-2.2.1@hearingtracker/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by abrambailey** [comment]
Nevermind, fixed with 
```
rvm default@mailcatcher --create do gem install mailcatcher
rvm wrapper default@mailcatcher --no-prefix mailcatcher catchmail
```
