### ISSUE TITLE
MC quits upon receiving message

### ISSUE THREAD

**Issue by jiripudil** [sj26/mailcatcher#285]
We are trying MC on our dev machine. However, it quits upon receiving a single message, without a hint of what's wrong. I tried running it with `-f -v`, with the following output:

```
==> SMTP: Received message from '<john.doe@example.com>' (7663 bytes)
2016-04-21 15:40:40 - Encoding::UndefinedConversionError - "\xC3" from ASCII-8BIT to UTF-8:
	/usr/local/share/gems/gems/activesupport-4.2.6/lib/active_support/core_ext/object/json.rb:34:in `encode'
	/usr/local/share/gems/gems/activesupport-4.2.6/lib/active_support/core_ext/object/json.rb:34:in `to_json'
	/usr/local/share/gems/gems/activesupport-4.2.6/lib/active_support/core_ext/object/json.rb:34:in `to_json_with_active_support_encoder'
	/usr/local/share/gems/gems/activesupport-4.2.6/lib/active_support/json/encoding.rb:57:in `to_json'
	/usr/share/gems/gems/json-1.7.7/lib/json/common.rb:224:in `generate'
	/usr/share/gems/gems/json-1.7.7/lib/json/common.rb:224:in `generate'
	/usr/local/share/gems/gems/activesupport-4.2.6/lib/active_support/json/encoding.rb:101:in `stringify'
	/usr/local/share/gems/gems/activesupport-4.2.6/lib/active_support/json/encoding.rb:35:in `encode'
	/usr/local/share/gems/gems/activesupport-4.2.6/lib/active_support/json/encoding.rb:22:in `encode'
	/usr/local/share/gems/gems/activesupport-4.2.6/lib/active_support/core_ext/object/json.rb:37:in `to_json_with_active_support_encoder'
	/usr/local/share/gems/gems/mailcatcher-0.6.4/lib/mail_catcher/web/application.rb:96:in `block in <class:Application>'
	/usr/local/share/gems/gems/sinatra-1.4.7/lib/sinatra/base.rb:1611:in `call'
	/usr/local/share/gems/gems/sinatra-1.4.7/lib/sinatra/base.rb:1611:in `block in compile!'
	/usr/local/share/gems/gems/sinatra-1.4.7/lib/sinatra/base.rb:975:in `[]'
	/usr/local/share/gems/gems/sinatra-1.4.7/lib/sinatra/base.rb:975:in `block (3 levels) in route!'
	/usr/local/share/gems/gems/sinatra-1.4.7/lib/sinatra/base.rb:994:in `route_eval'
	/usr/local/share/gems/gems/sinatra-1.4.7/lib/sinatra/base.rb:975:in `block (2 levels) in route!'
	/usr/local/share/gems/gems/sinatra-1.4.7/lib/sinatra/base.rb:1015:in `block in process_route'
	/usr/local/share/gems/gems/sinatra-1.4.7/lib/sinatra/base.rb:1013:in `catch'
	/usr/local/share/gems/gems/sinatra-1.4.7/lib/sinatra/base.rb:1013:in `process_route'
	/usr/local/share/gems/gems/sinatra-1.4.7/lib/sinatra/base.rb:973:in `block in route!'
	/usr/local/share/gems/gems/sinatra-1.4.7/lib/sinatra/base.rb:972:in `each'
	/usr/local/share/gems/gems/sinatra-1.4.7/lib/sinatra/base.rb:972:in `route!'
	/usr/local/share/gems/gems/sinatra-1.4.7/lib/sinatra/base.rb:1085:in `block in dispatch!'
	/usr/local/share/gems/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `block in invoke'
	/usr/local/share/gems/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `catch'
	/usr/local/share/gems/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `invoke'
	/usr/local/share/gems/gems/sinatra-1.4.7/lib/sinatra/base.rb:1082:in `dispatch!'
	/usr/local/share/gems/gems/sinatra-1.4.7/lib/sinatra/base.rb:907:in `block in call!'
	/usr/local/share/gems/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `block in invoke'
	/usr/local/share/gems/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `catch'
	/usr/local/share/gems/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `invoke'
	/usr/local/share/gems/gems/sinatra-1.4.7/lib/sinatra/base.rb:907:in `call!'
	/usr/local/share/gems/gems/sinatra-1.4.7/lib/sinatra/base.rb:895:in `call'
	/usr/local/share/gems/gems/rack-protection-1.5.3/lib/rack/protection/xss_header.rb:18:in `call'
	/usr/local/share/gems/gems/rack-protection-1.5.3/lib/rack/protection/path_traversal.rb:16:in `call'
	/usr/local/share/gems/gems/rack-protection-1.5.3/lib/rack/protection/json_csrf.rb:18:in `call'
	/usr/local/share/gems/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
	/usr/local/share/gems/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
	/usr/local/share/gems/gems/rack-protection-1.5.3/lib/rack/protection/frame_options.rb:31:in `call'
	/usr/local/share/gems/gems/rack-1.6.4/lib/rack/nulllogger.rb:9:in `call'
	/usr/local/share/gems/gems/rack-1.6.4/lib/rack/head.rb:13:in `call'
	/usr/local/share/gems/gems/sinatra-1.4.7/lib/sinatra/base.rb:182:in `call'
	/usr/local/share/gems/gems/sinatra-1.4.7/lib/sinatra/base.rb:2013:in `call'
	/usr/local/share/gems/gems/sinatra-1.4.7/lib/sinatra/base.rb:1487:in `block in call'
	/usr/local/share/gems/gems/sinatra-1.4.7/lib/sinatra/base.rb:1787:in `synchronize'
	/usr/local/share/gems/gems/sinatra-1.4.7/lib/sinatra/base.rb:1487:in `call'
	/usr/local/share/gems/gems/rack-1.6.4/lib/rack/urlmap.rb:66:in `block in call'
	/usr/local/share/gems/gems/rack-1.6.4/lib/rack/urlmap.rb:50:in `each'
	/usr/local/share/gems/gems/rack-1.6.4/lib/rack/urlmap.rb:50:in `call'
	/usr/local/share/gems/gems/rack-1.6.4/lib/rack/builder.rb:153:in `call'
	/usr/local/share/gems/gems/mailcatcher-0.6.4/lib/mail_catcher/web.rb:19:in `call'
	/usr/local/share/gems/gems/thin-1.5.1/lib/thin/connection.rb:81:in `block in pre_process'
	/usr/local/share/gems/gems/thin-1.5.1/lib/thin/connection.rb:79:in `catch'
	/usr/local/share/gems/gems/thin-1.5.1/lib/thin/connection.rb:79:in `pre_process'
	/usr/local/share/gems/gems/thin-1.5.1/lib/thin/connection.rb:54:in `process'
	/usr/local/share/gems/gems/thin-1.5.1/lib/thin/connection.rb:39:in `receive_data'
	/usr/local/share/gems/gems/eventmachine-1.0.9.1/lib/eventmachine.rb:193:in `run_machine'
	/usr/local/share/gems/gems/eventmachine-1.0.9.1/lib/eventmachine.rb:193:in `run'
	/usr/local/share/gems/gems/mailcatcher-0.6.4/lib/mail_catcher.rb:164:in `run!'
	/usr/local/share/gems/gems/mailcatcher-0.6.4/bin/mailcatcher:5:in `<top (required)>'
	/usr/local/bin/mailcatcher:23:in `load'
	/usr/local/bin/mailcatcher:23:in `<main>'
```

Funny thing is, it continued running. But when run in background, it just dies once it receives a single message. I don't know if the exception above is the cause or not though. Also, I'm not sure what `--no-quit` does exactly, but I gave it a shot anyway. No luck.

Any ideas what might be wrong or where to look for more clues?

**Comment by jiripudil** [comment]
This seems kinda related http://stackoverflow.com/questions/23309669/ruby-encode-xc3-from-ascii-8bit-to-utf-8-encodingundefinedconversionerr

**Comment by lucaspiller** [comment]
I spend too much time debugging this exception last week (unrelated to Mailcatcher) - it is raised when ActiveSupport tries to encode a string that is ASCII encoded, but contains UTF-8 characters (i.e. the character encoding on the string is wrong). It only happens if you use the ActiveSupport 4+ JSON encoder - if you use have Yajl/Oj/ActiveSupport < 4 it works fine.

In my case I was making HTTP requests that returned UTF-8 characters, but all the Ruby HTTP libraries return the response as ASCII (ignoring any content type response headers) - the fix was to add `.force_encoding('UTF-8')` to the string as I knew it would always be UTF-8. Maybe something like that is going on here?

**Comment by sj26** [comment]
Please try v0.6.5 and reopen with a fresh backtrace if you're still having issues.
