### ISSUE TITLE
Problems with character encoding

### ISSUE THREAD

**Issue by abr4xas** [sj26/mailcatcher#288]
Hello, i'm using phpmailer with slim framework and using mailcatcher to test all functionality. Everythings works as expected but i have some problems with character encoding with spanish words like: corazón, canción.

This is the output:

```bash
/var/lib/gems/2.1.0/gems/activesupport-4.2.6/lib/active_support/core_ext/object/json.rb:34:in `encode': "\xC3" from ASCII-8BIT to UTF-8 (Encoding::UndefinedConversionError)
	from /var/lib/gems/2.1.0/gems/activesupport-4.2.6/lib/active_support/core_ext/object/json.rb:34:in `to_json'
	from /var/lib/gems/2.1.0/gems/activesupport-4.2.6/lib/active_support/core_ext/object/json.rb:34:in `to_json_with_active_support_encoder'
	from /var/lib/gems/2.1.0/gems/activesupport-4.2.6/lib/active_support/json/encoding.rb:57:in `to_json'
	from /usr/lib/ruby/vendor_ruby/json/common.rb:223:in `generate'
	from /usr/lib/ruby/vendor_ruby/json/common.rb:223:in `generate'
	from /var/lib/gems/2.1.0/gems/activesupport-4.2.6/lib/active_support/json/encoding.rb:101:in `stringify'
	from /var/lib/gems/2.1.0/gems/activesupport-4.2.6/lib/active_support/json/encoding.rb:35:in `encode'
	from /var/lib/gems/2.1.0/gems/activesupport-4.2.6/lib/active_support/json/encoding.rb:22:in `encode'
	from /var/lib/gems/2.1.0/gems/activesupport-4.2.6/lib/active_support/core_ext/object/json.rb:37:in `to_json_with_active_support_encoder'
	from /var/lib/gems/2.1.0/gems/mailcatcher-0.6.4/lib/mail_catcher/web/application.rb:67:in `block (3 levels) in <class:Application>'
	from /var/lib/gems/2.1.0/gems/eventmachine-1.0.9.1/lib/em/channel.rb:43:in `call'
	from /var/lib/gems/2.1.0/gems/eventmachine-1.0.9.1/lib/em/channel.rb:43:in `block (3 levels) in push'
	from /var/lib/gems/2.1.0/gems/eventmachine-1.0.9.1/lib/em/channel.rb:43:in `each'
	from /var/lib/gems/2.1.0/gems/eventmachine-1.0.9.1/lib/em/channel.rb:43:in `block (2 levels) in push'
	from /var/lib/gems/2.1.0/gems/eventmachine-1.0.9.1/lib/em/channel.rb:43:in `each'
	from /var/lib/gems/2.1.0/gems/eventmachine-1.0.9.1/lib/em/channel.rb:43:in `block in push'
	from /var/lib/gems/2.1.0/gems/eventmachine-1.0.9.1/lib/eventmachine.rb:256:in `call'
	from /var/lib/gems/2.1.0/gems/eventmachine-1.0.9.1/lib/eventmachine.rb:256:in `schedule'
	from /var/lib/gems/2.1.0/gems/eventmachine-1.0.9.1/lib/em/channel.rb:43:in `push'
	from /var/lib/gems/2.1.0/gems/mailcatcher-0.6.4/lib/mail_catcher/mail.rb:57:in `block in add_message'
	from /var/lib/gems/2.1.0/gems/eventmachine-1.0.9.1/lib/eventmachine.rb:981:in `call'
	from /var/lib/gems/2.1.0/gems/eventmachine-1.0.9.1/lib/eventmachine.rb:981:in `block in run_deferred_callbacks'
	from /var/lib/gems/2.1.0/gems/eventmachine-1.0.9.1/lib/eventmachine.rb:978:in `times'
	from /var/lib/gems/2.1.0/gems/eventmachine-1.0.9.1/lib/eventmachine.rb:978:in `run_deferred_callbacks'
	from /var/lib/gems/2.1.0/gems/eventmachine-1.0.9.1/lib/eventmachine.rb:193:in `run_machine'
	from /var/lib/gems/2.1.0/gems/eventmachine-1.0.9.1/lib/eventmachine.rb:193:in `run'
	from /var/lib/gems/2.1.0/gems/mailcatcher-0.6.4/lib/mail_catcher.rb:164:in `run!'
	from /var/lib/gems/2.1.0/gems/mailcatcher-0.6.4/bin/mailcatcher:5:in `<top (required)>'
	from /usr/local/bin/mailcatcher:23:in `load'
	from /usr/local/bin/mailcatcher:23:in `<main>'
```

So, i don't know if this is a mailcatcher problem or it's form my phpmailer config.

**Comment by obviouser** [comment]
Just install magic_encoding gem and add in the top of file mail_catcher.rb the line
encoding = "utf-8"

**Comment by tnokovski** [comment]
Not sure if it's related, but we had the same problem on 0.6.4 and it's happening when a user is viewing the mailcatcher web interface (there is an active web socket) and a mail is sent via mailcatcher.

A workaround until this is really resolved that worked for us:

**Edit**: `/var/lib/gems/2.1.0/gems/mailcatcher-0.6.4/public/assets/mailcatcher.js `
_(note: replace 2.1.0 and 0.6.4 with the respective versions)_

Add `WebSocket=undefined;` in the beginning of the file.

This will disable web sockets and fallback to normal http requests. Messages list will be updated every second.

**Comment by longwave** [comment]
Sounds like the same problem as #201?

**Comment by sj26** [comment]
Please try v0.6.5 and reopen with a fresh backtrace if you're still having issues.
