### ISSUE TITLE
Mailcatcher just stopped working; Any ideas?

### ISSUE THREAD

**Issue by delwaterman** [sj26/mailcatcher#290]
OS X: Yosemite

```
12:01 $ mailcatcher
Starting MailCatcher
==> smtp://127.0.0.1:1025
==> http://127.0.0.1:1080
/Users/orion.delwaterman/.rvm/gems/ruby-2.2.4/gems/eventmachine-1.2.0.1/lib/eventmachine.rb:1489:in `event_callback': undefined method `close' for 14:Fixnum (NoMethodError)
	from /Users/orion.delwaterman/.rvm/gems/ruby-2.2.4/gems/eventmachine-1.2.0.1/lib/eventmachine.rb:194:in `run_machine'
	from /Users/orion.delwaterman/.rvm/gems/ruby-2.2.4/gems/eventmachine-1.2.0.1/lib/eventmachine.rb:194:in `run'
	from /Users/orion.delwaterman/.rvm/gems/ruby-2.2.4/gems/mailcatcher-0.2.4/lib/mail_catcher.rb:21:in `run'
	from /Users/orion.delwaterman/.rvm/gems/ruby-2.2.4/gems/mailcatcher-0.2.4/bin/mailcatcher:44:in `<top (required)>'
	from /Users/orion.delwaterman/.rvm/gems/ruby-2.2.4/bin/mailcatcher:22:in `load'
	from /Users/orion.delwaterman/.rvm/gems/ruby-2.2.4/bin/mailcatcher:22:in `<main>'
	from /Users/orion.delwaterman/.rvm/gems/ruby-2.2.4/bin/ruby_executable_hooks:15:in `eval'
	from /Users/orion.delwaterman/.rvm/gems/ruby-2.2.4/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by sj26** [comment]
That's a very old version of mailcatcher: 0.2.4.

Please try upgrading: `gem install mailcatcher`

**Comment by tuanphpvn-bluecom** [comment]
Mailcatcher have some  seriously problems. For example. It can work on cli environment but it is not work on web environment.

So I move to Mailhog. It is perfect fine now. Cheer.

**Comment by douglasresende** [comment]
Try this: bundle exec mailcatcher --http-ip 0.0.0.0

**Comment by lesliev** [comment]
According to the Readme: "Please don't put mailcatcher into your Gemfile"
