### ISSUE TITLE
Problems with umlauts

### ISSUE THREAD

**Issue by mhauri** [sj26/mailcatcher#304]
It seems that there is a problem with umlauts
### Steps to reproduce

```
$subject = 'Test';
$body = 'äöü';

if(mail('test@test.com', $subject, $body)) {
    echo 'sent';
} else {
    echo 'not sent';
}
```
### Expected result

sent
### Actual result

not sent

Sending mails with umlauts works fine as long as I don't use mailcatcher

**Comment by wuethrich44** [comment]
Here is an example stacktrace from version 6.5.0:
```ruby
Sep 20 15:25:42 sxdev mailcatcher[27098]: ==> SMTP: Received message from '<test@test.ch>' (282944 bytes)
Sep 20 15:25:42 sxdev mailcatcher[27098]: *** Error sending message through websocket: 
Sep 20 15:25:42 sxdev mailcatcher[27098]: Exception: "\xC3" from ASCII-8BIT to UTF-8
Sep 20 15:25:42 sxdev mailcatcher[27098]: Backtrace:
Sep 20 15:25:42 sxdev mailcatcher[27098]: /usr/lib/ruby/2.1.0/json/common.rb:223:in `encode'
Sep 20 15:25:42 sxdev mailcatcher[27098]: /usr/lib/ruby/2.1.0/json/common.rb:223:in `generate'
Sep 20 15:25:42 sxdev mailcatcher[27098]: /usr/lib/ruby/2.1.0/json/common.rb:223:in `generate'
Sep 20 15:25:42 sxdev mailcatcher[27098]: mailcatcher (0.6.5) lib/mail_catcher/web/application.rb:69:in `block (3 levels) in <class:Application>'
Sep 20 15:25:42 sxdev mailcatcher[27098]: eventmachine (1.0.9.1) lib/em/channel.rb:43:in `call'
Sep 20 15:25:42 sxdev mailcatcher[27098]: eventmachine (1.0.9.1) lib/em/channel.rb:43:in `block (3 levels) in push'
Sep 20 15:25:42 sxdev mailcatcher[27098]: eventmachine (1.0.9.1) lib/em/channel.rb:43:in `each'
Sep 20 15:25:42 sxdev mailcatcher[27098]: eventmachine (1.0.9.1) lib/em/channel.rb:43:in `block (2 levels) in push'
Sep 20 15:25:42 sxdev mailcatcher[27098]: eventmachine (1.0.9.1) lib/em/channel.rb:43:in `each'
Sep 20 15:25:42 sxdev mailcatcher[27098]: eventmachine (1.0.9.1) lib/em/channel.rb:43:in `block in push'
Sep 20 15:25:42 sxdev mailcatcher[27098]: eventmachine (1.0.9.1) lib/eventmachine.rb:256:in `call'
Sep 20 15:25:42 sxdev mailcatcher[27098]: eventmachine (1.0.9.1) lib/eventmachine.rb:256:in `schedule'
Sep 20 15:25:42 sxdev mailcatcher[27098]: eventmachine (1.0.9.1) lib/em/channel.rb:43:in `push'
Sep 20 15:25:42 sxdev mailcatcher[27098]: mailcatcher (0.6.5) lib/mail_catcher/mail.rb:57:in `block in add_message'
Sep 20 15:25:42 sxdev mailcatcher[27098]: eventmachine (1.0.9.1) lib/eventmachine.rb:981:in `call'
Sep 20 15:25:42 sxdev mailcatcher[27098]: eventmachine (1.0.9.1) lib/eventmachine.rb:981:in `block in run_deferred_callbacks'
Sep 20 15:25:42 sxdev mailcatcher[27098]: eventmachine (1.0.9.1) lib/eventmachine.rb:978:in `times'
Sep 20 15:25:42 sxdev mailcatcher[27098]: eventmachine (1.0.9.1) lib/eventmachine.rb:978:in `run_deferred_callbacks'
Sep 20 15:25:42 sxdev mailcatcher[27098]: eventmachine (1.0.9.1) lib/eventmachine.rb:193:in `run_machine'
Sep 20 15:25:42 sxdev mailcatcher[27098]: eventmachine (1.0.9.1) lib/eventmachine.rb:193:in `run'
Sep 20 15:25:42 sxdev mailcatcher[27098]: mailcatcher (0.6.5) lib/mail_catcher.rb:173:in `run!'
Sep 20 15:25:42 sxdev mailcatcher[27098]: mailcatcher (0.6.5) bin/mailcatcher:5:in `<top (required)>'
Sep 20 15:25:42 sxdev mailcatcher[27098]: /usr/local/bin/mailcatcher:23:in `load'
Sep 20 15:25:42 sxdev mailcatcher[27098]: /usr/local/bin/mailcatcher:23:in `<main>'
Sep 20 15:25:42 sxdev mailcatcher[27098]: Please submit this as an issue at http://github.com/sj26/mailcatcher/issues
```
When I refresh the page the mails show up but the HTML is not rendered. When I switch from plain text to HTML the email is rendered correctly.

**Comment by sj26** [comment]
That looks like you're sending utf-8 characters as part of a plain text encoding, which mail clients will expect to be ASCII. Can you try something like:

```php
$subject = 'Test';
$headers = "Content-Type: text/plain; charset=utf-8"
$body = 'äöü';

if(mail('test@test.com', $subject, $body, $headers)) {
    echo 'sent';
} else {
    echo 'not sent';
}
```

If this doesn't work please re-open with a full message body as PHP sends it so I can reproduce.
