### ISSUE TITLE
UTF-8 character encoding issue persists with v0.6.5

### ISSUE THREAD

**Issue by pundurs** [sj26/mailcatcher#311]
Hello!

I was among the people having utf-8 encode issues with mailcatcher. After upgrading to mailcatcher 0.6.5., the issue still persists:

```
==> SMTP: Received message from '<noreply@example.com> size=1631' (1712 bytes)
2016-10-04 15:39:44 - Encoding::UndefinedConversionError - "\xC5" from ASCII-8BIT to UTF-8:
    /usr/lib/ruby/2.3.0/json/common.rb:224:in `encode'
    /usr/lib/ruby/2.3.0/json/common.rb:224:in `generate'
    /usr/lib/ruby/2.3.0/json/common.rb:224:in `generate'
    /var/lib/gems/2.3.0/gems/mailcatcher-0.6.5/lib/mail_catcher/web/application.rb:94:in `block in <class:Application>'
    /var/lib/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1611:in `call'
    /var/lib/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1611:in `block in compile!'
    /var/lib/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:975:in `block (3 levels) in route!'
    /var/lib/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:994:in `route_eval'
    /var/lib/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:975:in `block (2 levels) in route!'
    /var/lib/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1015:in `block in process_route'
    /var/lib/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1013:in `catch'
    /var/lib/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1013:in `process_route'
    /var/lib/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:973:in `block in route!'
    /var/lib/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:972:in `each'
    /var/lib/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:972:in `route!'
    /var/lib/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1085:in `block in dispatch!'
    /var/lib/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `block in invoke'
    /var/lib/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `catch'
    /var/lib/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `invoke'
    /var/lib/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1082:in `dispatch!'
    /var/lib/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:907:in `block in call!'
    /var/lib/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `block in invoke'
    /var/lib/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `catch'
    /var/lib/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `invoke'
    /var/lib/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:907:in `call!'
    /var/lib/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:895:in `call'
    /var/lib/gems/2.3.0/gems/rack-protection-1.5.3/lib/rack/protection/xss_header.rb:18:in `call'
    /var/lib/gems/2.3.0/gems/rack-protection-1.5.3/lib/rack/protection/path_traversal.rb:16:in `call'
    /var/lib/gems/2.3.0/gems/rack-protection-1.5.3/lib/rack/protection/json_csrf.rb:18:in `call'
    /var/lib/gems/2.3.0/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
    /var/lib/gems/2.3.0/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
    /var/lib/gems/2.3.0/gems/rack-protection-1.5.3/lib/rack/protection/frame_options.rb:31:in `call'
    /var/lib/gems/2.3.0/gems/rack-1.6.4/lib/rack/nulllogger.rb:9:in `call'
    /var/lib/gems/2.3.0/gems/rack-1.6.4/lib/rack/head.rb:13:in `call'
    /var/lib/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:182:in `call'
    /var/lib/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:2013:in `call'
    /var/lib/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1487:in `block in call'
    /var/lib/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1787:in `synchronize'
    /var/lib/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1487:in `call'
    /var/lib/gems/2.3.0/gems/rack-1.6.4/lib/rack/urlmap.rb:66:in `block in call'
    /var/lib/gems/2.3.0/gems/rack-1.6.4/lib/rack/urlmap.rb:50:in `each'
    /var/lib/gems/2.3.0/gems/rack-1.6.4/lib/rack/urlmap.rb:50:in `call'
    /var/lib/gems/2.3.0/gems/rack-1.6.4/lib/rack/builder.rb:153:in `call'
    /var/lib/gems/2.3.0/gems/mailcatcher-0.6.5/lib/mail_catcher/web.rb:19:in `call'
    /var/lib/gems/2.3.0/gems/thin-1.5.1/lib/thin/connection.rb:81:in `block in pre_process'
    /var/lib/gems/2.3.0/gems/thin-1.5.1/lib/thin/connection.rb:79:in `catch'
    /var/lib/gems/2.3.0/gems/thin-1.5.1/lib/thin/connection.rb:79:in `pre_process'
    /var/lib/gems/2.3.0/gems/thin-1.5.1/lib/thin/connection.rb:54:in `process'
    /var/lib/gems/2.3.0/gems/thin-1.5.1/lib/thin/connection.rb:39:in `receive_data'
    /var/lib/gems/2.3.0/gems/eventmachine-1.0.9.1/lib/eventmachine.rb:193:in `run_machine'
    /var/lib/gems/2.3.0/gems/eventmachine-1.0.9.1/lib/eventmachine.rb:193:in `run'
    /var/lib/gems/2.3.0/gems/mailcatcher-0.6.5/lib/mail_catcher.rb:173:in `run!'
    /var/lib/gems/2.3.0/gems/mailcatcher-0.6.5/bin/mailcatcher:5:in `<top (required)>'
    /usr/local/bin/mailcatcher:23:in `load'
    /usr/local/bin/mailcatcher:23:in `<main>'
```

**Comment by tombu** [comment]
Hi, I can confirm this issue still persists in 0.6.5.

**Comment by roneichiarandi** [comment]
```
Exception: "\xC3" from ASCII-8BIT to UTF-8
    Backtrace:
       /usr/lib/ruby/2.1.0/json/common.rb:223:in `encode'
       /usr/lib/ruby/2.1.0/json/common.rb:223:in `generate'
       /usr/lib/ruby/2.1.0/json/common.rb:223:in `generate'
       mailcatcher (0.6.5) lib/mail_catcher/web/application.rb:69:in `block (3 levels) in <class:Application>'
       eventmachine (1.0.9.1) lib/em/channel.rb:43:in `call'
       eventmachine (1.0.9.1) lib/em/channel.rb:43:in `block (3 levels) in push'
       eventmachine (1.0.9.1) lib/em/channel.rb:43:in `each'
       eventmachine (1.0.9.1) lib/em/channel.rb:43:in `block (2 levels) in push'
       eventmachine (1.0.9.1) lib/em/channel.rb:43:in `each'
       eventmachine (1.0.9.1) lib/em/channel.rb:43:in `block in push'
       eventmachine (1.0.9.1) lib/eventmachine.rb:256:in `call'
       eventmachine (1.0.9.1) lib/eventmachine.rb:256:in `schedule'
       eventmachine (1.0.9.1) lib/em/channel.rb:43:in `push'
       mailcatcher (0.6.5) lib/mail_catcher/mail.rb:57:in `block in add_message'
       eventmachine (1.0.9.1) lib/eventmachine.rb:981:in `call'
       eventmachine (1.0.9.1) lib/eventmachine.rb:981:in `block in run_deferred_callbacks'
       eventmachine (1.0.9.1) lib/eventmachine.rb:978:in `times'
       eventmachine (1.0.9.1) lib/eventmachine.rb:978:in `run_deferred_callbacks'
       eventmachine (1.0.9.1) lib/eventmachine.rb:193:in `run_machine'
       eventmachine (1.0.9.1) lib/eventmachine.rb:193:in `run'
       mailcatcher (0.6.5) lib/mail_catcher.rb:173:in `run!'
       mailcatcher (0.6.5) bin/mailcatcher:5:in `<top (required)>'
       /usr/local/bin/mailcatcher:23:in `load'
       /usr/local/bin/mailcatcher:23:in `<main>'
```

The problem persists when send special characters, but the application don't crash/stop more...

**Comment by sj26** [comment]
Anybody affected by this issue: could you please upload a message body which triggers this error so I can reproduce and perhaps fix this issue.

**Comment by roneichiarandi** [comment]
@sj26 The error happens when the message body has special characters like **"á"**

**Comment by sj26** [comment]
I'm sorry it's not working for you, but it works fine for me:

![screenshot 2016-12-10 22 04 33](https://cloud.githubusercontent.com/assets/14028/21072897/b0e23ffc-bf24-11e6-814a-4e53ce655a80.png)

Could you please provide an example message which doesn't work?

Note that valid email message bodies don't have utf-8 in the middle of a message body unencoded, you must encode it suitably. Most libraries for sending email should handle this for you pretty sensibly. Here's the example I tried using Ruby's mail gem, which is how mailcatcher reads email:

```sh
$ ruby --require mail
irb> Mail.defaults { delivery_method :smtp, address: "localhost", port: 1025 }
irb> Mail.new(to: "foo@example.com", from: "bar@example.com", subject: "Héllo", body: "Héllo").deliver
Non US-ASCII detected and no charset defined.
Defaulting to UTF-8, set your own if this is incorrect.
=> #<Mail::Message:70286438842840, Multipart: false, Headers: <Date: Sat, 10 Dec 2016 22:03:55 +1100>, <From: bar@example.com>, <To: foo@example.com>, <Message-ID: <584be11b4fedf_f54e3fecd483f9b8284c8@Bumblebee.local.mail>>, <Subject: Héllo>, <Mime-Version: 1.0>, <Content-Type: text/plain>, <Content-Transfer-Encoding: base64>>
```

And the message body it sent:

```http
Date: Sat, 10 Dec 2016 22:03:55 +1100
From: bar@example.com
To: foo@example.com
Message-ID: <584be11b4fedf_f54e3fecd483f9b8284c8@Bumblebee.local.mail>
Subject: =?UTF-8?Q?H=C3=A9llo?=
Mime-Version: 1.0
Content-Type: text/plain;
 charset=UTF-8
Content-Transfer-Encoding: base64

SMOpbGxv
```

**Comment by sj26** [comment]
I'm going to close this for now. If somebody has an issue with character encodings in mailcatcher please provide the full message body (with headers and mime) along with the errors it is triggering as a new issue.
