### ISSUE TITLE
symbol MD5_Init, version OPENSSL_1.0.0 not defined in file libcrypto.so.1.0.0 with link time reference

### ISSUE THREAD

**Issue by thomaspaulson** [sj26/mailcatcher#317]
I came across the same error mention in https://github.com/sj26/mailcatcher/issues/230,
When I run  ruby -r digest/md5 -r openssl -e "puts OpenSSL::VERSION"  getting response 1.1.0

```
/home/thomas/.rbenv/versions/2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require': /home/thomas/.rbenv/versions/2.3.1/lib/ruby/2.3.0/i686-linux/digest/md5.so: symbol MD5_Init, version OPENSSL_1.0.0 not defined in file libcrypto.so.1.0.0 with link time reference - /home/thomas/.rbenv/versions/2.3.1/lib/ruby/2.3.0/i686-linux/digest/md5.so (LoadError)
	from /home/thomas/.rbenv/versions/2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /home/thomas/.rbenv/versions/2.3.1/lib/ruby/2.3.0/net/smtp.rb:24:in `<top (required)>'
	from /home/thomas/.rbenv/versions/2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /home/thomas/.rbenv/versions/2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /home/thomas/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/mail-2.6.4/lib/mail.rb:9:in `<module:Mail>'
	from /home/thomas/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/mail-2.6.4/lib/mail.rb:3:in `<top (required)>'
	from /home/thomas/.rbenv/versions/2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /home/thomas/.rbenv/versions/2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /home/thomas/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/mailcatcher-0.6.5/bin/catchmail:7:in `rescue in <top (required)>'
	from /home/thomas/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/mailcatcher-0.6.5/bin/catchmail:3:in `<top (required)>'
	from /home/thomas/.rbenv/versions/2.3.1/bin/catchmail:23:in `load'
	from /home/thomas/.rbenv/versions/2.3.1/bin/catchmail:23:in `<main>'
```

**Comment by sj26** [comment]
Sorry, I have no idea why this happens! Maybe you need to recompile your rbenv ruby? If you can figure it out and would like to contribute it would be most welcome.

**Comment by sj26** [comment]
You could also try: `gem pristine eventmachine`

This seems like a environment issue, closing without further details.
