### ISSUE TITLE
Undefined conversion Error ASCII-8BIT to UTF-8

### ISSUE THREAD

**Issue by Erwane** [sj26/mailcatcher#322]
Full UTF-8 debug

related to #311 & #201 

```
*** Error sending message through websocket: {"id"=>2, "sender"=>"<hidden@email.com>", "recipients"=>["<hidden@email.com>"], "subject"=>"[Ormiel] Réinitialisation du mot de passe", "source"=>"From: =?UTF-8?B?Q29tcHRhYmlsaXTDqSBPcm1pZWw=?= <hidden@email.com>\r\nTo: Name <hidden@email.com>\r\nDate: Thu, 29 Dec 2016 08:38:43 +0000\r\nMessage-ID: <93e16340e2634d91b3c1ee8b0c824673@compta.local.phea.fr>\r\nSubject: [Ormiel] =?UTF-8?B?UsOpaW5pdGlhbGlzYXRpb24gZHUgbW90IGRlIHBhc3Nl?=\r\nMIME-Version: 1.0\r\nContent-Type: text/html; charset=UTF-8\r\nContent-Transfer-Encoding: 8bit\r\n\r\n<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01//EN\">\r\n<html>\r\n<head>\r\n    <title>Email/html</title>\r\n</head>\r\n<body>\r\n    <p>Bonjour Name,</p>\r\n\r\n<p>Vous avez demand\xC3\xA9 un nouveau mot de passe pour le site Comptabilit\xC3\xA9.</p>\r\n<p>Si vous n'avez pas fait cette demande, ignorez cet email.</p>\r\n<br>\r\n<p>Si vous souhaitez un nouveau mot de passe, cliquez sur le lien ci-dessous</p>\r\n<p><a href=\"http://compta.local.phea.fr/auth/renew/eb84d2aa\">Je r\xC3\xA9initialise mon mot de passe</a></p>\r\n</body>\r\n</html>\r\n\r\n\r\n\r\n", "size"=>"896", "type"=>"text/html", "created_at"=>#<DateTime: 2016-12-29T08:38:43+00:00 ((2457752j,31123s,0n),+0s,2299161j)>}
    Exception: "\xC3" from ASCII-8BIT to UTF-8
    Backtrace:
       /usr/lib/ruby/2.3.0/json/common.rb:224:in `encode'
       /usr/lib/ruby/2.3.0/json/common.rb:224:in `generate'
       /usr/lib/ruby/2.3.0/json/common.rb:224:in `generate'
       mailcatcher (0.6.5) lib/mail_catcher/web/application.rb:69:in `block (3 levels) in <class:Application>'
       eventmachine (1.0.9.1) lib/em/channel.rb:43:in `block (3 levels) in push'
       eventmachine (1.0.9.1) lib/em/channel.rb:43:in `each'
       eventmachine (1.0.9.1) lib/em/channel.rb:43:in `block (2 levels) in push'
       eventmachine (1.0.9.1) lib/em/channel.rb:43:in `each'
       eventmachine (1.0.9.1) lib/em/channel.rb:43:in `block in push'
       eventmachine (1.0.9.1) lib/eventmachine.rb:256:in `schedule'
       eventmachine (1.0.9.1) lib/em/channel.rb:43:in `push'
       mailcatcher (0.6.5) lib/mail_catcher/mail.rb:57:in `block in add_message'
       eventmachine (1.0.9.1) lib/eventmachine.rb:981:in `block in run_deferred_callbacks'
       eventmachine (1.0.9.1) lib/eventmachine.rb:978:in `times'
       eventmachine (1.0.9.1) lib/eventmachine.rb:978:in `run_deferred_callbacks'
       eventmachine (1.0.9.1) lib/eventmachine.rb:193:in `run_machine'
       eventmachine (1.0.9.1) lib/eventmachine.rb:193:in `run'
       mailcatcher (0.6.5) lib/mail_catcher.rb:173:in `run!'
       mailcatcher (0.6.5) bin/mailcatcher:5:in `<top (required)>'
       /usr/local/bin/mailcatcher:23:in `load'
       /usr/local/bin/mailcatcher:23:in `<main>'
```

**mail source**
```
From: =?UTF-8?B?Q29tcHRhYmlsaXTDqSBPcm1pZWw=?= <hidden@email.com>
To: Name <hidden@email.com>
Date: Thu, 29 Dec 2016 08:38:30 +0000
Message-ID: <43670e26007741bdbc30af51fb06d641@compta.local.phea.fr>
Subject: [Ormiel] =?UTF-8?B?UsOpaW5pdGlhbGlzYXRpb24gZHUgbW90IGRlIHBhc3Nl?=
MIME-Version: 1.0
Content-Type: text/html; charset=UTF-8
Content-Transfer-Encoding: 8bit

<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01//EN">
<html>
<head>
    <title>Email/html</title>
</head>
<body>
    <p>Bonjour Olivier,</p>

<p>Vous avez demandé un nouveau mot de passe pour le site Comptabilité.</p>
<p>Si vous n'avez pas fait cette demande, ignorez cette email.</p>
<br>
<p>Si vous souhaitez un nouveau mot de passe, cliquez sur le lien ci-dessous</p>
<p><a href="http://compta.local.phea.fr/auth/renew/8d6a9c93">Je réinitialise mon mot de passe</a></p>
</body>
</html>
```

```
*** LOCAL GEMS ***

activesupport (4.2.7.1)
bigdecimal (1.2.8)
daemons (1.2.4)
did_you_mean (1.0.0)
eventmachine (1.0.9.1)
i18n (0.7.0)
io-console (0.4.5)
json (1.8.3)
mail (2.6.4)
mailcatcher (0.6.5, 0.6.4)
mime-types (3.1)
mime-types-data (3.2016.0521)
minitest (5.9.0)
net-telnet (0.1.1)
power_assert (0.2.7)
psych (2.0.17)
rack (1.6.5)
rack-protection (1.5.3)
rake (10.5.0)
rdoc (4.2.1)
sinatra (1.4.7)
skinny (0.2.4)
sqlite3 (1.3.12)
test-unit (3.1.7)
thin (1.5.1)
thread_safe (0.3.5)
tilt (2.0.5)
tzinfo (1.2.2)
```

```
2016-12-29 09:35:46 - Encoding::UndefinedConversionError - "\xC3" from ASCII-8BIT to UTF-8:
	/usr/lib/ruby/2.3.0/json/common.rb:224:in `encode'
	/usr/lib/ruby/2.3.0/json/common.rb:224:in `generate'
	/usr/lib/ruby/2.3.0/json/common.rb:224:in `generate'
	/var/lib/gems/2.3.0/gems/mailcatcher-0.6.5/lib/mail_catcher/web/application.rb:94:in `block in <class:Application>'
	/var/lib/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1611:in `call'
	/var/lib/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1611:in `block in compile!'
	/var/lib/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:975:in `block (3 levels) in route!'
	/var/lib/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:994:in `route_eval'
	/var/lib/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:975:in `block (2 levels) in route!'
	/var/lib/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1015:in `block in process_route'
	/var/lib/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1013:in `catch'
	/var/lib/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1013:in `process_route'
	/var/lib/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:973:in `block in route!'
	/var/lib/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:972:in `each'
	/var/lib/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:972:in `route!'
	/var/lib/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1085:in `block in dispatch!'
	/var/lib/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `block in invoke'
	/var/lib/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `catch'
	/var/lib/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `invoke'
	/var/lib/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1082:in `dispatch!'
	/var/lib/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:907:in `block in call!'
	/var/lib/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `block in invoke'
	/var/lib/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `catch'
	/var/lib/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `invoke'
	/var/lib/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:907:in `call!'
	/var/lib/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:895:in `call'
	/var/lib/gems/2.3.0/gems/rack-protection-1.5.3/lib/rack/protection/xss_header.rb:18:in `call'
	/var/lib/gems/2.3.0/gems/rack-protection-1.5.3/lib/rack/protection/path_traversal.rb:16:in `call'
	/var/lib/gems/2.3.0/gems/rack-protection-1.5.3/lib/rack/protection/json_csrf.rb:18:in `call'
	/var/lib/gems/2.3.0/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
	/var/lib/gems/2.3.0/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
	/var/lib/gems/2.3.0/gems/rack-protection-1.5.3/lib/rack/protection/frame_options.rb:31:in `call'
	/var/lib/gems/2.3.0/gems/rack-1.6.5/lib/rack/nulllogger.rb:9:in `call'
	/var/lib/gems/2.3.0/gems/rack-1.6.5/lib/rack/head.rb:13:in `call'
	/var/lib/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:182:in `call'
	/var/lib/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:2013:in `call'
	/var/lib/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1487:in `block in call'
	/var/lib/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1787:in `synchronize'
	/var/lib/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1487:in `call'
	/var/lib/gems/2.3.0/gems/rack-1.6.5/lib/rack/urlmap.rb:66:in `block in call'
	/var/lib/gems/2.3.0/gems/rack-1.6.5/lib/rack/urlmap.rb:50:in `each'
	/var/lib/gems/2.3.0/gems/rack-1.6.5/lib/rack/urlmap.rb:50:in `call'
	/var/lib/gems/2.3.0/gems/rack-1.6.5/lib/rack/builder.rb:153:in `call'
	/var/lib/gems/2.3.0/gems/mailcatcher-0.6.5/lib/mail_catcher/web.rb:19:in `call'
	/var/lib/gems/2.3.0/gems/thin-1.5.1/lib/thin/connection.rb:81:in `block in pre_process'
	/var/lib/gems/2.3.0/gems/thin-1.5.1/lib/thin/connection.rb:79:in `catch'
	/var/lib/gems/2.3.0/gems/thin-1.5.1/lib/thin/connection.rb:79:in `pre_process'
	/var/lib/gems/2.3.0/gems/thin-1.5.1/lib/thin/connection.rb:54:in `process'
	/var/lib/gems/2.3.0/gems/thin-1.5.1/lib/thin/connection.rb:39:in `receive_data'
	/var/lib/gems/2.3.0/gems/eventmachine-1.0.9.1/lib/eventmachine.rb:193:in `run_machine'
	/var/lib/gems/2.3.0/gems/eventmachine-1.0.9.1/lib/eventmachine.rb:193:in `run'
	/var/lib/gems/2.3.0/gems/mailcatcher-0.6.5/lib/mail_catcher.rb:173:in `run!'
	/var/lib/gems/2.3.0/gems/mailcatcher-0.6.5/bin/mailcatcher:5:in `<top (required)>'
	/usr/local/bin/mailcatcher:23:in `load'
	/usr/local/bin/mailcatcher:23:in `<main>'
```

**Comment by sj26** [comment]
Ah, I can replicate this! But I had to netcat to mailcatcher directly to perform an SMTP exchange and paste your exact mail message:

```
$ nc localhost 1025
EHLO localhost
250-Ok EventMachine SMTP Server
250-NO-SOLICITING
250 SIZE 20000000
MAIL FROM:<hidden@email.com>
250 Ok
RCPT TO:<hidden@email.com>
250 Ok
DATA
354 Send it
From: =?UTF-8?B?Q29tcHRhYmlsaXTDqSBPcm1pZWw=?= <hidden@email.com>
To: Name <hidden@email.com>
Date: Thu, 29 Dec 2016 08:38:30 +0000
Message-ID: <43670e26007741bdbc30af51fb06d641@compta.local.phea.fr>
Subject: [Ormiel] =?UTF-8?B?UsOpaW5pdGlhbGlzYXRpb24gZHUgbW90IGRlIHBhc3Nl?=
MIME-Version: 1.0
Content-Type: text/html; charset=UTF-8
Content-Transfer-Encoding: 8bit

<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01//EN">
<html>
<head>
    <title>Email/html</title>
</head>
<body>
    <p>Bonjour Olivier,</p>

<p>Vous avez demandé un nouveau mot de passe pour le site Comptabilité.</p>
<p>Si vous n'avez pas fait cette demande, ignorez cette email.</p>
<br>
<p>Si vous souhaitez un nouveau mot de passe, cliquez sur le lien ci-dessous</p>
<p><a href="http://compta.local.phea.fr/auth/renew/8d6a9c93">Je réinitialise mon mot de passe</a></p>
</body>
</html>
.
250 Message accepted
QUIT
221 Ok
```

The message is received and stored, but then I get the error you quote from the thread sending the websocket message:

```
Exception: "\xC3" from ASCII-8BIT to UTF-8
```

This is because Eventmachine's SMTP server has just read the message as a bunch of bytes and marked it as "ASCII" encoded, stored it as such, and when we actually try to *use* the message for presentation it attempts to convert it to the JSON-compatible UTF-8 encoding, but it has invalid ASCII characters.

It took me a little while to figure this out: `Content-Transfer-Encoding: 8bit` is an [SMTP extension](https://tools.ietf.org/html/rfc6152). Eventmachine's SMTP server does not support it, and should be throwing an error earlier in the exchange. Your Mail/SMTP library is submitted an 8-bit encoded message to an SMTP server that is not advertising 8-bit compatibility. It should be formatting as quoted-printable or similar. Running this message through catchmail (which uses the mail gem which sanitizes quite a lot and respects SMTP capabilities) actually changes it to something the SMTP server supports:

```
Date: Thu, 29 Dec 2016 08:38:30 +0000
From: =?UTF-8?B?Q29tcHRhYmlsaXTDqSBPcm1pZWw=?= <hidden@email.com>
To: Name <hidden@email.com>
Message-ID: <43670e26007741bdbc30af51fb06d641@compta.local.phea.fr>
Subject: =?UTF-8?Q?[Ormiel]_R=C3=A9initialisation_du_mot_de_passe?=
Mime-Version: 1.0
Content-Type: text/html;
 charset=UTF-8
Content-Transfer-Encoding: quoted-printable

<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01//EN">
<html>
<head>
    <title>Email/html</title>
</head>
<body>
    <p>Bonjour Olivier,</p>

<p>Vous avez demand=C3=A9 un nouveau mot de passe pour le site Comptabili=
t=C3=A9.</p>
<p>Si vous n'avez pas fait cette demande, ignorez cette email.</p>
<br>
<p>Si vous souhaitez un nouveau mot de passe, cliquez sur le lien ci-dess=
ous</p>
<p><a href=3D"http://compta.local.phea.fr/auth/renew/8d6a9c93">Je r=C3=A9=
initialise mon mot de passe</a></p>
</body>
</html>
```

But the message content is exactly the same.

If you'd like to fix the SMTP server in Eventmachine to support 8-bit transfer encoding implicitly (which is kinda incorrect but lenient) then this might go away?

**Comment by Erwane** [comment]
I'm using CakePHP 3.3 Mailer\Email library for sending emails. 

```php
    /**
     * Charset the email body is sent in
     *
     * @var string
     */
    public $charset = 'utf-8';

    /**
     * 8Bit character sets
     *
     * @var array
     */
    protected $_charset8bit = ['UTF-8', 'SHIFT_JIS'];

    /**
     * Return the Content-Transfer Encoding value based on the set charset
     *
     * @return string
     */
    protected function _getContentTransferEncoding()
    {
        $charset = strtoupper($this->charset);
        if (in_array($charset, $this->_charset8bit)) {
            return '8bit';
        }

        return '7bit';
    }

    public function getHeaders(array $include = [])
    {
         // (snip code)
         $headers['Content-Transfer-Encoding'] = $this->_getContentTransferEncoding();
    }
```

8bit is not a common way ?

**Comment by Erwane** [comment]
Same email with PHPMailer and base64 or quoted-printable Encoding work perfectly.

I confirm problem is with 7bit & 8bit .

**Comment by sj26** [comment]
UTF-8 is not valid over the wire for SMTP unless the mail server advertises 8-bit encoding, which MailCatcher does not. If you a receiving errors here then I'm afraid you or your mail library is not correctly encoding your sent email and you should probably make sure that is fixed so your mail is received correctly.

**Comment by Erwane** [comment]
Oops : https://en.wikipedia.org/wiki/Extended_SMTP#8BITMIME
So mailcatcher does not support BUT it is a mailcatcher pb, not mail library.
But it's okay, the thing is to known that limitation.

**Comment by pensiero** [comment]
I'm using the dockerized version of mailcatcher (https://hub.docker.com/r/schickling/mailcatcher/).
Strange thing is that the very first time it worked, then it started displaying the error described in this issue.

Is there any solution about this problem?

**Comment by pensiero** [comment]
I'm using the dockerized version of mailcatcher (https://hub.docker.com/r/schickling/mailcatcher/), and when I click on a mail on the UI, it appears the problem described in this issue.

Is there any solution about this problem?

**Comment by kvokka** [comment]
I've just got the same result with really weird situation. 

This is the breaking snippet:

```
   <div style="display:none; white-space:nowrap; font:15px courier; line-height:0;"> &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </div>
```

While

```
   <div style="display:none; white-space:nowrap; font:15px courier; line-height:0;"></div>
```

works fine. IDK why. And have no ideas, but may be will be for somebody useful.
