### ISSUE TITLE
 Exception: "\xE7" from ASCII-8BIT to UTF-8

### ISSUE THREAD

**Issue by Zeyshi** [sj26/mailcatcher#324]
```
SMTP: Received message from '<info@almatinki.com>' (671 bytes)
*** Error sending message through websocket: {"id"=>3602, "sender"=>"<info@almatinki.com>", "recipients"=>["<leila.taip@yandex.kz>", "<leila.taip@yandex.kz>"], "subject"=>"\xE7\xCC\xD5\xC2\xCF\xCB\xC9\xCA \xCD\xC9\xCE\xC5\xD4", "source"=>"Received: from unknown (HELO localhost) (info@almatinki.com@75.206.138.62)\r\n\tby 213.57.76.56 with ESMTPA; Tue, 10 Jan 2017 09:30:53 -0800\r\nMessage-ID: <002901d26b66$e337b200$4bce8a3e@homePC>\r\nFrom: \"Charlotte Robbins\" <info@almatinki.com>\r\nTo: <leila.taip@yandex.kz>\r\nSubject: \xE7\xCC\xD5\xC2\xCF\xCB\xC9\xCA \xCD\xC9\xCE\xC5\xD4\r\nDate: Tue, 10 Jan 2017 09:22:16 -0800\r\nMIME-Version: 1.0\r\nContent-Type: text/plain;\r\n\tformat=flowed;\r\n\tcharset=\"KOI8-R\";\r\n\treply-type=original\r\nContent-Transfer-Encoding: 8bit\r\nX-Priority: 3\r\nX-MSMail-Priority: Normal\r\nX-Mailer: Microsoft Outlook Express 6.00.2800.1106\r\nX-MimeOLE: Produced By Microsoft MimeOLE V6.00.2800.1106\r\n\r\n\xF3\xC5\xCB\xD3\xD5\xC1\xCC\xD8\xCE\xD9\xC5 \xC1\xCC\xCD\xC1\xD4\xC9\xCE\xCB\xC9 http://almatinki.com/\r\n\r\n", "size"=>"671", "type"=>"text/plain", "created_at"=>#<DateTime: 2017-01-10T17:28:54+00:00 ((2457764j,62934s,0n),+0s,2299161j)>}
    Exception: "\xE7" from ASCII-8BIT to UTF-8
    Backtrace:
       json (2.0.2) lib/json/common.rb:224:in `encode'
       json (2.0.2) lib/json/common.rb:224:in `generate'
       json (2.0.2) lib/json/common.rb:224:in `generate'
       mailcatcher (0.6.5) lib/mail_catcher/web/application.rb:69:in `block (3 levels) in <class:Application>'
       eventmachine (1.0.9.1) lib/em/channel.rb:43:in `block (3 levels) in push'
       eventmachine (1.0.9.1) lib/em/channel.rb:43:in `each'
       eventmachine (1.0.9.1) lib/em/channel.rb:43:in `block (2 levels) in push'
       eventmachine (1.0.9.1) lib/em/channel.rb:43:in `each'
       eventmachine (1.0.9.1) lib/em/channel.rb:43:in `block in push'
       eventmachine (1.0.9.1) lib/eventmachine.rb:256:in `schedule'
       eventmachine (1.0.9.1) lib/em/channel.rb:43:in `push'
       mailcatcher (0.6.5) lib/mail_catcher/mail.rb:57:in `block in add_message'
       eventmachine (1.0.9.1) lib/eventmachine.rb:981:in `block in run_deferred_callbacks'
       eventmachine (1.0.9.1) lib/eventmachine.rb:978:in `times'
       eventmachine (1.0.9.1) lib/eventmachine.rb:978:in `run_deferred_callbacks'
       eventmachine (1.0.9.1) lib/eventmachine.rb:193:in `run_machine'
       eventmachine (1.0.9.1) lib/eventmachine.rb:193:in `run'
       mailcatcher (0.6.5) lib/mail_catcher.rb:173:in `run!'
       mailcatcher (0.6.5) bin/mailcatcher:5:in `<top (required)>'
       C:/Ruby23-x64/bin/mailcatcher:22:in `load'
       C:/Ruby23-x64/bin/mailcatcher:22:in `<main>'
```

**Comment by zvinger** [comment]
I have same issue too

**Comment by Erwane** [comment]
same as #322

**Comment by 199911** [comment]
I got the same problem

**Comment by 199911** [comment]
Btw I am using this docker image
and the error message is

```
2017-02-07 09:17:44 - Encoding::UndefinedConversionError - "\xE2" from ASCII-8BIT to UTF-8:
	/usr/lib/ruby/2.1.0/json/common.rb:223:in `encode'
	/usr/lib/ruby/2.1.0/json/common.rb:223:in `generate'
	/usr/lib/ruby/2.1.0/json/common.rb:223:in `generate'
	/var/lib/gems/2.1.0/gems/mailcatcher-0.6.5/lib/mail_catcher/web/application.rb:94:in `block in <class:Application>'
	/var/lib/gems/2.1.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1611:in `call'
	/var/lib/gems/2.1.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1611:in `block in compile!'
	/var/lib/gems/2.1.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:975:in `[]'
	/var/lib/gems/2.1.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:975:in `block (3 levels) in route!'
	/var/lib/gems/2.1.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:994:in `route_eval'
	/var/lib/gems/2.1.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:975:in `block (2 levels) in route!'
	/var/lib/gems/2.1.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1015:in `block in process_route'
	/var/lib/gems/2.1.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1013:in `catch'
	/var/lib/gems/2.1.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1013:in `process_route'
	/var/lib/gems/2.1.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:973:in `block in route!'
	/var/lib/gems/2.1.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:972:in `each'
	/var/lib/gems/2.1.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:972:in `route!'
	/var/lib/gems/2.1.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1085:in `block in dispatch!'
	/var/lib/gems/2.1.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `block in invoke'
	/var/lib/gems/2.1.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `catch'
	/var/lib/gems/2.1.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `invoke'
	/var/lib/gems/2.1.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1082:in `dispatch!'
	/var/lib/gems/2.1.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:907:in `block in call!'
	/var/lib/gems/2.1.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `block in invoke'
	/var/lib/gems/2.1.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `catch'
	/var/lib/gems/2.1.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `invoke'
	/var/lib/gems/2.1.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:907:in `call!'
	/var/lib/gems/2.1.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:895:in `call'
	/var/lib/gems/2.1.0/gems/rack-protection-1.5.3/lib/rack/protection/xss_header.rb:18:in `call'
	/var/lib/gems/2.1.0/gems/rack-protection-1.5.3/lib/rack/protection/path_traversal.rb:16:in `call'
	/var/lib/gems/2.1.0/gems/rack-protection-1.5.3/lib/rack/protection/json_csrf.rb:18:in `call'
	/var/lib/gems/2.1.0/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
	/var/lib/gems/2.1.0/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
	/var/lib/gems/2.1.0/gems/rack-protection-1.5.3/lib/rack/protection/frame_options.rb:31:in `call'
	/var/lib/gems/2.1.0/gems/rack-1.6.4/lib/rack/nulllogger.rb:9:in `call'
	/var/lib/gems/2.1.0/gems/rack-1.6.4/lib/rack/head.rb:13:in `call'
	/var/lib/gems/2.1.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:182:in `call'
	/var/lib/gems/2.1.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:2013:in `call'
	/var/lib/gems/2.1.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1487:in `block in call'
	/var/lib/gems/2.1.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1787:in `synchronize'
	/var/lib/gems/2.1.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1487:in `call'
	/var/lib/gems/2.1.0/gems/rack-1.6.4/lib/rack/urlmap.rb:66:in `block in call'
	/var/lib/gems/2.1.0/gems/rack-1.6.4/lib/rack/urlmap.rb:50:in `each'
	/var/lib/gems/2.1.0/gems/rack-1.6.4/lib/rack/urlmap.rb:50:in `call'
	/var/lib/gems/2.1.0/gems/rack-1.6.4/lib/rack/builder.rb:153:in `call'
	/var/lib/gems/2.1.0/gems/mailcatcher-0.6.5/lib/mail_catcher/web.rb:19:in `call'
	/var/lib/gems/2.1.0/gems/thin-1.5.1/lib/thin/connection.rb:81:in `block in pre_process'
	/var/lib/gems/2.1.0/gems/thin-1.5.1/lib/thin/connection.rb:79:in `catch'
	/var/lib/gems/2.1.0/gems/thin-1.5.1/lib/thin/connection.rb:79:in `pre_process'
	/var/lib/gems/2.1.0/gems/thin-1.5.1/lib/thin/connection.rb:54:in `process'
	/var/lib/gems/2.1.0/gems/thin-1.5.1/lib/thin/connection.rb:39:in `receive_data'
	/var/lib/gems/2.1.0/gems/eventmachine-1.0.9.1/lib/eventmachine.rb:193:in `run_machine'
	/var/lib/gems/2.1.0/gems/eventmachine-1.0.9.1/lib/eventmachine.rb:193:in `run'
	/var/lib/gems/2.1.0/gems/mailcatcher-0.6.5/lib/mail_catcher.rb:173:in `run!'
	/var/lib/gems/2.1.0/gems/mailcatcher-0.6.5/bin/mailcatcher:5:in `<top (required)>'
	/usr/local/bin/mailcatcher:23:in `load'
	/usr/local/bin/mailcatcher:23:in `<main>'
```

**Comment by 199911** [comment]
Seems related to php mailer's update. Are you guys also using php mailer?

**Comment by elik-ru** [comment]
This patch fixes the issue. 

https://github.com/sj26/mailcatcher/pull/329

**Comment by sj26** [comment]
UTF-8 is not valid over the wire for SMTP unless the mail server advertises 8-bit encoding, which MailCatcher does not. If you a receiving errors here then I'm afraid you or your mail library is not correctly encoding your sent email and you should probably make sure that is fixed so your mail is received correctly.

**Comment by elik-ru** [comment]
I'm using regular Rails 5 mailer. Of cause it's transfer encoding is quoted-printable ascii. But inside it has one html part with utf8 encoding. What's wrong ?
