### ISSUE TITLE
"\xE3" from ASCII-8BIT to UTF-8

### ISSUE THREAD

**Issue by lrezende** [sj26/mailcatcher#326]
```
==> SMTP: Received message from '<test@test.com>' (276 bytes)
*** Error sending message through websocket: {"id"=>60, "sender"=>"<test@test.com>", "recipients"=>["<test2@test.com>"], "subject"=>"subject test at 15:16:08", "source"=>"Date: Tue, 31 Jan 2017 15:16:08 -0300\r\nFrom: \"\"<test@test.com>\r\nTo: \"\" <test2@test.com>\r\nSubject: subject test at 15:16:08\r\nContent-Type: text/html\r\ncharset=ISO-8859-1X-Mailer: MAILER_ID\r\nX-Priority: 3\r\n\r\n<body><h1>strange message with some strange chars... \xE3\xBF\xE1\xE9</h1></body>\r\n", "size"=>"276", "type"=>"text/html", "created_at"=>#<DateTime: 2017-01-31T18:16:08+00:00 ((2457785j,65768s,0n),+0s,2299161j)>}
    Exception: "\xE3" from ASCII-8BIT to UTF-8
    Backtrace:
       /usr/local/lib/ruby/2.2.0/json/common.rb:223:in `encode'
       /usr/local/lib/ruby/2.2.0/json/common.rb:223:in `generate'
       /usr/local/lib/ruby/2.2.0/json/common.rb:223:in `generate'
       mailcatcher (0.6.5) lib/mail_catcher/web/application.rb:69:in `block (3 levels) in <class:Application>'
       eventmachine (1.0.9.1) lib/em/channel.rb:43:in `call'
       eventmachine (1.0.9.1) lib/em/channel.rb:43:in `block (3 levels) in push'
       eventmachine (1.0.9.1) lib/em/channel.rb:43:in `each'
       eventmachine (1.0.9.1) lib/em/channel.rb:43:in `block (2 levels) in push'
       eventmachine (1.0.9.1) lib/em/channel.rb:43:in `each'
       eventmachine (1.0.9.1) lib/em/channel.rb:43:in `block in push'
       eventmachine (1.0.9.1) lib/eventmachine.rb:256:in `call'
       eventmachine (1.0.9.1) lib/eventmachine.rb:256:in `schedule'
       eventmachine (1.0.9.1) lib/em/channel.rb:43:in `push'
       mailcatcher (0.6.5) lib/mail_catcher/mail.rb:57:in `block in add_message'
       eventmachine (1.0.9.1) lib/eventmachine.rb:981:in `call'
       eventmachine (1.0.9.1) lib/eventmachine.rb:981:in `block in run_deferred_callbacks'
       eventmachine (1.0.9.1) lib/eventmachine.rb:978:in `times'
       eventmachine (1.0.9.1) lib/eventmachine.rb:978:in `run_deferred_callbacks'
       eventmachine (1.0.9.1) lib/eventmachine.rb:193:in `run_machine'
       eventmachine (1.0.9.1) lib/eventmachine.rb:193:in `run'
       mailcatcher (0.6.5) lib/mail_catcher.rb:173:in `run!'
       mailcatcher (0.6.5) bin/mailcatcher:5:in `<top (required)>'
       /usr/local/bundle/bin/mailcatcher:22:in `load'
       /usr/local/bundle/bin/mailcatcher:22:in `<main>'

```

The message is

`<body><h1>strange message with some strange chars... ãẽáé</h1></body>`

**Comment by lrezende** [comment]
Same as #322 

Solved with some treatment before sending mail... Basically encoding the text and sending Content-Transfer-Encoding=quoted-printable

**Comment by lrezende** [comment]
Is this just a websocket problem? Is there an option to disable it?
