### ISSUE TITLE
Exception: "\xCE" from ASCII-8BIT to UTF-8

### ISSUE THREAD

**Issue by Rapid0s** [sj26/mailcatcher#345]
`*** Error sending message through websocket: {"id"=>4, "sender"=>"<info@testing.com>", "recipients"=>["<testing1s@gmail.com>"], "subject"=>"TEST 123", "source"=>"Date: Wed, 2 Aug 2017 22:42:33 +0300\r\nTo: testing <testinggmail.com>\r\nFrom: \"info@testing.com\" <info@tresorhotels.com>\r\nReply-To: \"info@testing.com\" <info@testingcom>\r\nSubject: TEST 123\r\nMessage-ID: <2d0a611f48ad108caa6c70fc048acc5f@rapid0s.ns>\r\nX-Mailer: NS Mailer\r\nMIME-Version: 1.0\r\nContent-Type: multipart/alternative;\r\n\tboundary=\"b1_2d0a611f48ad108caa6c70fc048acc5f\"\r\nContent-Transfer-Encoding: 8bit\r\n\r\nThis is a multi-part message in MIME format.\r\n\r\n--b1_2d0a611f48ad108caa6c70fc048acc5f\r\nContent-Type: text/plain; charset=utf-8\r\nContent-Transfer-Encoding: 8bit\r\n\r\na\xCE\xB1\r\n\r\n\r\n--b1_2d0a611f48ad108caa6c70fc048acc5f\r\nContent-Type: text/html; charset=utf-8\r\nContent-Transfer-Encoding: 8bit\r\n\r\n<html><body><strong>a\xCE\xB1</strong></body></html>\r\n\r\n\r\n\r\n--b1_2d0a611f48ad108caa6c70fc048acc5f--\r\n\r\n", "size"=>"808", "type"=>"multipart/alternative", "created_at"=>#<DateTime: 2017-08-02T19:42:33+00:00 ((2457968j,70953s,0n),+0s,2299161j)>}
    Exception: "\xCE" from ASCII-8BIT to UTF-8
    Backtrace:
       /usr/lib/ruby/2.1.0/json/common.rb:223:in `encode'
       /usr/lib/ruby/2.1.0/json/common.rb:223:in `generate'
       /usr/lib/ruby/2.1.0/json/common.rb:223:in `generate'
       mailcatcher (0.7.0.beta1) lib/mail_catcher/web/application.rb:67:in `block (3 levels) in <class:Application>'
       eventmachine (1.0.9.1) lib/em/channel.rb:43:in `call'
       eventmachine (1.0.9.1) lib/em/channel.rb:43:in `block (3 levels) in push'
       eventmachine (1.0.9.1) lib/em/channel.rb:43:in `each'
       eventmachine (1.0.9.1) lib/em/channel.rb:43:in `block (2 levels) in push'
       eventmachine (1.0.9.1) lib/em/channel.rb:43:in `each'
       eventmachine (1.0.9.1) lib/em/channel.rb:43:in `block in push'
       eventmachine (1.0.9.1) lib/eventmachine.rb:256:in `call'
       eventmachine (1.0.9.1) lib/eventmachine.rb:256:in `schedule'
       eventmachine (1.0.9.1) lib/em/channel.rb:43:in `push'
       mailcatcher (0.7.0.beta1) lib/mail_catcher/mail.rb:57:in `block in add_message'
       eventmachine (1.0.9.1) lib/eventmachine.rb:981:in `call'
       eventmachine (1.0.9.1) lib/eventmachine.rb:981:in `block in run_deferred_callbacks'
       eventmachine (1.0.9.1) lib/eventmachine.rb:978:in `times'
       eventmachine (1.0.9.1) lib/eventmachine.rb:978:in `run_deferred_callbacks'
       eventmachine (1.0.9.1) lib/eventmachine.rb:193:in `run_machine'
       eventmachine (1.0.9.1) lib/eventmachine.rb:193:in `run'
       mailcatcher (0.7.0.beta1) lib/mail_catcher.rb:190:in `run!'
       mailcatcher (0.7.0.beta1) bin/mailcatcher:5:in `<top (required)>'
       /usr/local/bin/mailcatcher:23:in `load'
       /usr/local/bin/mailcatcher:23:in `<main>'
    Please submit this as an issue at http://github.com/sj26/mailcatcher/issues`

When I include Greek characters in the body like "α" I get this crash report.
My html body is:
`<html><body><strong>aα</strong></body></html>`

**Comment by Rapid0s** [comment]
My bad  same as [#322](https://github.com/sj26/mailcatcher/issues/322)
It would be nice to be able to read correctly the entire email ... but it is what it is :)
