### ISSUE TITLE
Failing tests

### ISSUE THREAD

**Issue by EdwinHoksberg** [sj26/mailcatcher#351]
Hi, I think the tests are not working. When I run `bundle exec rake test` I get these errors:
```
Finished in 3.362824s, 2.0816 runs/s, 2.9737 assertions/s.

  1) Error:
MailCatcher#test_0001_catches and displays a plain text message as plain text and source:
Selenium::WebDriver::Error::NoSuchElementError: {"errorMessage":"Unable to find element with xpath './/table/tbody/tr[1]'","request":{"headers":{"Accept":"application/json","Accept-Encoding":"gzip;q=1.0,deflate;q=0.6,identity;q=0.3","Connection":"close","Content-Length":"48","Content-Type":"application/json; charset=utf-8","Host":"127.0.0.1:8910","User-Agent":"Ruby"},"httpVersion":"1.1","method":"POST","post":"{\"using\":\"xpath\",\"value\":\".//table/tbody/tr[1]\"}","url":"/element","urlParsed":{"anchor":"","query":"","file":"element","directory":"/","path":"/element","relative":"/element","port":"","host":"","password":"","user":"","userInfo":"","authority":"","protocol":"","source":"/element","queryKey":{},"chunks":["element"]},"urlOriginal":"/session/fa976470-87dc-11e7-86bd-bba24ff9716d/element/:wdc:1503476882692/element"}} (org.openqa.selenium.NoSuchElementException)
    /var/lib/gems/2.3.0/gems/selenium-webdriver-3.5.1/lib/selenium/webdriver/remote/response.rb:69:in `assert_ok'
    /var/lib/gems/2.3.0/gems/selenium-webdriver-3.5.1/lib/selenium/webdriver/remote/response.rb:32:in `initialize'
    /var/lib/gems/2.3.0/gems/selenium-webdriver-3.5.1/lib/selenium/webdriver/remote/http/common.rb:83:in `new'
    /var/lib/gems/2.3.0/gems/selenium-webdriver-3.5.1/lib/selenium/webdriver/remote/http/common.rb:83:in `create_response'
    /var/lib/gems/2.3.0/gems/selenium-webdriver-3.5.1/lib/selenium/webdriver/remote/http/default.rb:107:in `request'
    /var/lib/gems/2.3.0/gems/selenium-webdriver-3.5.1/lib/selenium/webdriver/remote/http/common.rb:61:in `call'
    /var/lib/gems/2.3.0/gems/selenium-webdriver-3.5.1/lib/selenium/webdriver/remote/bridge.rb:170:in `execute'
    /var/lib/gems/2.3.0/gems/selenium-webdriver-3.5.1/lib/selenium/webdriver/remote/oss/bridge.rb:579:in `execute'
    /var/lib/gems/2.3.0/gems/selenium-webdriver-3.5.1/lib/selenium/webdriver/remote/oss/bridge.rb:547:in `find_element_by'
    /var/lib/gems/2.3.0/gems/selenium-webdriver-3.5.1/lib/selenium/webdriver/common/search_context.rb:62:in `find_element'
    /tmp/mailcatcher/spec/acceptance_spec.rb:58:in `message_row_element'
    /tmp/mailcatcher/spec/acceptance_spec.rb:62:in `message_from_element'
    /tmp/mailcatcher/spec/acceptance_spec.rb:100:in `block (2 levels) in <top (required)>'
    /usr/lib/ruby/vendor_ruby/minitest/test.rb:107:in `block (3 levels) in run'
    /usr/lib/ruby/vendor_ruby/minitest/test.rb:204:in `capture_exceptions'
    /usr/lib/ruby/vendor_ruby/minitest/test.rb:104:in `block (2 levels) in run'
    /usr/lib/ruby/vendor_ruby/minitest/test.rb:255:in `time_it'
    /usr/lib/ruby/vendor_ruby/minitest/test.rb:103:in `block in run'
    /usr/lib/ruby/vendor_ruby/minitest.rb:350:in `on_signal'
    /usr/lib/ruby/vendor_ruby/minitest/test.rb:275:in `with_info_handler'
    /usr/lib/ruby/vendor_ruby/minitest/test.rb:102:in `run'
    /usr/lib/ruby/vendor_ruby/minitest.rb:839:in `run_one_method'
    /usr/lib/ruby/vendor_ruby/minitest.rb:324:in `run_one_method'
    /usr/lib/ruby/vendor_ruby/minitest.rb:311:in `block (2 levels) in run'
    /usr/lib/ruby/vendor_ruby/minitest.rb:310:in `each'
    /usr/lib/ruby/vendor_ruby/minitest.rb:310:in `block in run'
    /usr/lib/ruby/vendor_ruby/minitest.rb:350:in `on_signal'
    /usr/lib/ruby/vendor_ruby/minitest.rb:337:in `with_info_handler'
    /usr/lib/ruby/vendor_ruby/minitest.rb:309:in `run'
    /usr/lib/ruby/vendor_ruby/minitest.rb:159:in `block in __run'
    /usr/lib/ruby/vendor_ruby/minitest.rb:159:in `map'
    /usr/lib/ruby/vendor_ruby/minitest.rb:159:in `__run'
    /usr/lib/ruby/vendor_ruby/minitest.rb:136:in `run'
    /usr/lib/ruby/vendor_ruby/minitest.rb:63:in `block in autorun'

  2) Failure:
MailCatcher#test_0003_catches and displays a multipart message as text, html and source [/tmp/mailcatcher/spec/acceptance_spec.rb:168]:
Expected: "Test Multipart Mail"
  Actual: "Plain mail"

  3) Failure:
MailCatcher#test_0002_catches and displays an html message as html and source [/tmp/mailcatcher/spec/acceptance_spec.rb:134]:
Expected: "Test HTML Mail"
  Actual: "Test Attachment Mail"

7 runs, 10 assertions, 2 failures, 1 errors, 4 skips
```

When I run them again, I get an error again at the subject checks, but this time for a different subject. It seems like some sort of race condition. I don't have enough ruby knowledge to look into this, so could someone please fix the tests?

**Comment by sj26** [comment]
The build is passing [on travis](https://travis-ci.org/sj26/mailcatcher)! Maybe you need to install chrome or chromedriver?
