### ISSUE TITLE
Can not start mailcatcher

### ISSUE THREAD

**Issue by bandanh** [sj26/mailcatcher#354]
I used mailcatcher for more then a year and it worked like a charm but now ... :-(

When I try to start mailcatcher on  MacOS Sierra.
 ```
$ ruby -v
ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-darwin16]
$ gem -v
2.6.13
```
I get the Error Message:
```
$ mailcatcher
/usr/local/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:68:in `require': dlopen(/usr/local/lib/ruby/gems/2.4.0/gems/thin-1.5.1/lib/thin_parser.bundle, 9): Library not loaded: /usr/local/opt/ruby/lib/libruby.2.4.0.dylib (LoadError)
  Referenced from: /usr/local/lib/ruby/gems/2.4.0/gems/thin-1.5.1/lib/thin_parser.bundle
  Reason: image not found - /usr/local/lib/ruby/gems/2.4.0/gems/thin-1.5.1/lib/thin_parser.bundle
	from /usr/local/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /usr/local/lib/ruby/gems/2.4.0/gems/thin-1.5.1/lib/thin.rb:39:in `<top (required)>'
	from /usr/local/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /usr/local/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /usr/local/lib/ruby/gems/2.4.0/gems/mailcatcher-0.6.5/lib/mail_catcher.rb:16:in `<top (required)>'
	from /usr/local/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /usr/local/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /usr/local/lib/ruby/gems/2.4.0/gems/mailcatcher-0.6.5/bin/mailcatcher:3:in `<top (required)>'
	from /usr/local/bin/mailcatcher:22:in `load'
	from /usr/local/bin/mailcatcher:22:in `<main>'
```
All Gems should be up to date.

**Comment by sj26** [comment]
Have you reinstalled ruby or something recently? It looks like your installed version of thin can't talk to your installed version of ruby.

Try:

```
gem pristine --all
```

**Comment by bandanh** [comment]
wow, that fixed it, thank you so much
