### ISSUE TITLE
Update gem Thin to ~> 1.7

### ISSUE THREAD

**Issue by 5minpause** [sj26/mailcatcher#355]
Mailcatcher is currently using Thin in version `~> 1.5.0`. This version has a deprecation warning:

```
/Users/holger/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/thin-1.5.1/lib/thin/server.rb:104: warning: constant ::Fixnum is deprecated
```

We cannot update Thin in Mailcatcher as it is used by sj26/skinny as well.

Update: I forked Skinny and opened this PR: https://github.com/sj26/skinny/pull/4 Unfortunately Skinny doesn't have tests, so I am not sure whether I broke something with this.

Update 2:
When running the tests after using my Skinny fork with the new Thin version, I get this error:

```
mailcatcher master % bund exec rake --trace
** Invoke default (first_time)
** Invoke test (first_time)
** Invoke assets (first_time)
** Execute assets
** Execute test
/Users/holger/projects/ruby/github/mailcatcher/spec/acceptance_spec.rb:146: warning: ambiguous first argument; put parentheses or a space even after `/' operator
/Users/holger/projects/ruby/github/mailcatcher/spec/acceptance_spec.rb:180: warning: ambiguous first argument; put parentheses or a space even after `/' operator
/Users/holger/projects/ruby/github/mailcatcher/lib/mail_catcher.rb:142: warning: ambiguous first argument; put parentheses or a space even after `-' operator
/Users/holger/projects/ruby/github/mailcatcher/lib/mail_catcher.rb:249: warning: ambiguous first argument; put parentheses or a space even after `-' operator

File does not exist:

rake aborted!
Command failed with status (1): [ruby -w -I"lib" -I"/Users/holger/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/rake-12.1.0/lib" "/Users/holger/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/rake-12.1.0/lib/rake/rake_test_loader.rb" "spec/acceptance_spec.rb" ]
/Users/holger/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/rake-12.1.0/lib/rake/testtask.rb:130:in `block (3 levels) in define'
/Users/holger/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/rake-12.1.0/lib/rake/file_utils.rb:57:in `sh'
/Users/holger/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/rake-12.1.0/lib/rake/file_utils.rb:105:in `ruby'
/Users/holger/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/rake-12.1.0/lib/rake/testtask.rb:117:in `block (2 levels) in define'
/Users/holger/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/rake-12.1.0/lib/rake/file_utils_ext.rb:59:in `verbose'
/Users/holger/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/rake-12.1.0/lib/rake/testtask.rb:111:in `block in define'
/Users/holger/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/rake-12.1.0/lib/rake/task.rb:251:in `block in execute'
/Users/holger/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/rake-12.1.0/lib/rake/task.rb:251:in `each'
/Users/holger/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/rake-12.1.0/lib/rake/task.rb:251:in `execute'
/Users/holger/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/rake-12.1.0/lib/rake/task.rb:195:in `block in invoke_with_call_chain'
/Users/holger/.rbenv/versions/2.4.1/lib/ruby/2.4.0/monitor.rb:214:in `mon_synchronize'
[…]
```

I am currently not sure how to proceed.

**Comment by sj26** [comment]
There is a deprecation warning, yes, but as far as I know nothing is brown at the moment? Perhaps ruby 3 will be the impetus to fix. 😅

**Comment by sj26** [comment]
Deprecation warnings aren't errors, and mailcatcher seems to still be working. Closing.
