### ISSUE TITLE
Exception: "\xC2" from ASCII-8BIT to UTF-8

### ISSUE THREAD

**Issue by chris13524** [sj26/mailcatcher#364]
```
chris13524@lemon ~ % docker run --rm -p 1025:1025 -p 1080:1080 schickling/mailcatcher
Starting MailCatcher
==> smtp://0.0.0.0:1025
/usr/local/bundle/gems/thin-1.5.1/lib/thin/server.rb:104: warning: constant ::Fixnum is deprecated
==> http://0.0.0.0:1080
==> SMTP: Received message from '<chris@iamchris.email> SIZE=426' (426 bytes)
*** Error sending message through websocket: {"id"=>1, "sender"=>"<chris@iamchris.email> SIZE=426", "recipients"=>["<Chris@hichris.com>"], "subject"=>"f", "source"=>"To: \"Chris@hichris.com\" <Chris@hichris.com>\r\nFrom: Chris Smith <chris@iamchris.email>\r\nSubject: f\r\nMessage-ID: <c4ab22a8-45ee-7c3d-447e-14a95720961d@iamchris.email>\r\nDate: Sun, 11 Feb 2018 13:30:24 -0500\r\nUser-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:52.0) Gecko/20100101\r\n Thunderbird/52.5.0\r\nMIME-Version: 1.0\r\nContent-Type: text/plain; charset=utf-8\r\nContent-Transfer-Encoding: 8bit\r\nContent-Language: en-US\r\n\r\nf\xC2\xA0\xC2\xA0\xC2\xA0\r\n\r\n", "size"=>"426", "type"=>"text/plain", "created_at"=>#<DateTime: 2018-02-11T18:30:24+00:00 ((2458161j,66624s,0n),+0s,2299161j)>}
    Exception: "\xC2" from ASCII-8BIT to UTF-8
    Backtrace:
       /usr/local/lib/ruby/2.4.0/json/common.rb:224:in `encode'
       /usr/local/lib/ruby/2.4.0/json/common.rb:224:in `generate'
       /usr/local/lib/ruby/2.4.0/json/common.rb:224:in `generate'
       mailcatcher (0.6.5) lib/mail_catcher/web/application.rb:69:in `block (3 levels) in <class:Application>'
       eventmachine (1.0.9.1) lib/em/channel.rb:43:in `block (3 levels) in push'
       eventmachine (1.0.9.1) lib/em/channel.rb:43:in `each'
       eventmachine (1.0.9.1) lib/em/channel.rb:43:in `block (2 levels) in push'
       eventmachine (1.0.9.1) lib/em/channel.rb:43:in `each'
       eventmachine (1.0.9.1) lib/em/channel.rb:43:in `block in push'
       eventmachine (1.0.9.1) lib/eventmachine.rb:256:in `schedule'
       eventmachine (1.0.9.1) lib/em/channel.rb:43:in `push'
       mailcatcher (0.6.5) lib/mail_catcher/mail.rb:57:in `block in add_message'
       eventmachine (1.0.9.1) lib/eventmachine.rb:981:in `block in run_deferred_callbacks'
       eventmachine (1.0.9.1) lib/eventmachine.rb:978:in `times'
       eventmachine (1.0.9.1) lib/eventmachine.rb:978:in `run_deferred_callbacks'
       eventmachine (1.0.9.1) lib/eventmachine.rb:193:in `run_machine'
       eventmachine (1.0.9.1) lib/eventmachine.rb:193:in `run'
       mailcatcher (0.6.5) lib/mail_catcher.rb:173:in `run!'
       mailcatcher (0.6.5) bin/mailcatcher:5:in `<top (required)>'
       /usr/local/bundle/bin/mailcatcher:23:in `load'
       /usr/local/bundle/bin/mailcatcher:23:in `<main>'
    Please submit this as an issue at http://github.com/sj26/mailcatcher/issues
```

**Comment by Bandi017** [comment]
same here !!!

**Comment by znz** [comment]
I think it is bug of mail sender, not mailcatcher.
see https://github.com/sj26/mailcatcher/issues/322
