### ISSUE TITLE
Catchmail doesn't accept 8bit Content-Transfer-Encoding with UTF-8 characters

### ISSUE THREAD

**Issue by Revisor** [sj26/mailcatcher#371]
Hello,
I was wondering why our test emails didn't appear in Mailcatcher and why our tests kept failing. I traced it to an issue in `catchmail` when sending emails with `Content-Transfer-Encoding: 8bit` and UTF-8 characters in the body. I can provide a short sample.

First, the environment:

```
$ ruby -v
ruby 1.9.3p484 (2013-11-22 revision 43786) [x86_64-linux]
$ gem list
*** LOCAL GEMS ***

autoprefixer-rails (5.2.1)
bundler (1.16.1)
chunky_png (1.3.1)
compass (1.0.1)
compass-core (1.0.1)
compass-import-once (1.0.5)
daemons (1.2.6)
eventmachine (1.0.9.1)
execjs (2.5.2)
ffi (1.9.5)
json (1.8.3)
mail (2.7.0)
mailcatcher (0.6.5)
mime-types (2.99.3)
mini_mime (1.0.0)
multi_json (1.10.1)
rack (1.6.9)
rack-protection (1.5.5)
rb-fsevent (0.9.4)
rb-inotify (0.9.5)
sass (3.3.14)
sass-media_query_combiner (0.0.7)
sinatra (1.4.8)
skinny (0.2.4)
sqlite3 (1.3.13)
thin (1.5.1)
tilt (2.0.8)
```
This works:
File `mail.txt`
```
To: my@example.com
Subject: Test
From: me@example.com
Content-Type: text/plain; charset=UTF-8
Content-Transfer-Encoding: quoted-printable

H=C3=A1ll=C3=B3
```
Command
``` bash
catchmail < mail.txt
```

This doesn't work:
File `nomail.txt`
```
To: my@example.com
Subject: Test
From: me@example.com
Content-Type: text/plain; charset=UTF-8
Content-Transfer-Encoding: 8bit

Hálló
```
Command
```bash
$ catchmail < nomail.txt
/var/lib/gems/1.9.1/gems/mail-2.7.0/lib/mail/check_delivery_params.rb:13:in `check_from': SMTP From address may not be blank: nil (ArgumentError)
        from /var/lib/gems/1.9.1/gems/mail-2.7.0/lib/mail/check_delivery_params.rb:6:in `check'
        from /var/lib/gems/1.9.1/gems/mail-2.7.0/lib/mail/network/delivery_methods/smtp_connection.rb:52:in `deliver!'
        from /var/lib/gems/1.9.1/gems/mail-2.7.0/lib/mail/network/delivery_methods/smtp.rb:101:in `block in deliver!'
        from /usr/lib/ruby/1.9.1/net/smtp.rb:520:in `start'
        from /var/lib/gems/1.9.1/gems/mail-2.7.0/lib/mail/network/delivery_methods/smtp.rb:109:in `start_smtp_session'
        from /var/lib/gems/1.9.1/gems/mail-2.7.0/lib/mail/network/delivery_methods/smtp.rb:100:in `deliver!'
        from /var/lib/gems/1.9.1/gems/mail-2.7.0/lib/mail/message.rb:2160:in `do_delivery'
        from /var/lib/gems/1.9.1/gems/mail-2.7.0/lib/mail/message.rb:262:in `deliver'
        from /var/lib/gems/1.9.1/gems/mailcatcher-0.6.5/bin/catchmail:71:in `<top (required)>'
        from /usr/local/bin/catchmail:23:in `load'
        from /usr/local/bin/catchmail:23:in `<main>'
```
`Catchmail` used to accept these emails with UTF-8/8bit before, but it doesn't now. I might know the exact working version on Monday provided my colleague hasn't updated his VM yet.

Thank you for Mailcatcher and for your help.

**Comment by sj26** [comment]
Oh dear! I think ruby 1.9.3 was ascii by default, before ruby 2.0 made it utf-8 by default. Maybe try using `LC_ALL=en_US.UTF-8` in your environment, or add `# encoding: utf-8` as the second line in the `catchmail` script? Or see if you can upgrade to ruby 2.0+.

**Comment by sj26** [comment]
This should tell you which encoding Ruby is using:

```
$ ruby -e 'puts Encoding.default_external'
UTF-8
```

**Comment by Revisor** [comment]
Hello, thank you for your tips. I tried all three, but I still can't get it working
```bash
$ ruby -e 'puts Encoding.default_external'
UTF-8
$ export LC_ALL=en_US.UTF-8
$ catchmail < nomail.txt
/usr/share/rvm/gems/ruby-2.4.1/gems/mail-2.7.0/lib/mail/check_delivery_params.rb:13:in `check_from': SMTP From address may not be blank: nil (ArgumentError)
        from /usr/share/rvm/gems/ruby-2.4.1/gems/mail-2.7.0/lib/mail/check_delivery_params.rb:6:in `check'
        from /usr/share/rvm/gems/ruby-2.4.1/gems/mail-2.7.0/lib/mail/network/delivery_methods/smtp_connection.rb:52:in `deliver!'
        from /usr/share/rvm/gems/ruby-2.4.1/gems/mail-2.7.0/lib/mail/network/delivery_methods/smtp.rb:101:in `block in deliver!'
        from /usr/share/rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/net/smtp.rb:519:in `start'
        from /usr/share/rvm/gems/ruby-2.4.1/gems/mail-2.7.0/lib/mail/network/delivery_methods/smtp.rb:109:in `start_smtp_session'
        from /usr/share/rvm/gems/ruby-2.4.1/gems/mail-2.7.0/lib/mail/network/delivery_methods/smtp.rb:100:in `deliver!'
        from /usr/share/rvm/gems/ruby-2.4.1/gems/mail-2.7.0/lib/mail/message.rb:2160:in `do_delivery'
        from /usr/share/rvm/gems/ruby-2.4.1/gems/mail-2.7.0/lib/mail/message.rb:262:in `deliver'
        from /usr/share/rvm/gems/ruby-2.4.1/gems/mailcatcher-0.6.5/bin/catchmail:71:in `<top (required)>'
        from /usr/share/rvm/gems/ruby-2.4.1/bin/catchmail:23:in `load'
        from /usr/share/rvm/gems/ruby-2.4.1/bin/catchmail:23:in `<main>'
        from /usr/share/rvm/gems/ruby-2.4.1/bin/ruby_executable_hooks:15:in `eval'
        from /usr/share/rvm/gems/ruby-2.4.1/bin/ruby_executable_hooks:15:in `<main>'
```
Why does Mail say `check_from': SMTP From address may not be blank: nil (ArgumentError)` when it's not about the From address at all?

Shall I contact the authors of Mail?

Thank you for your patience.

**Comment by Revisor** [comment]
Ok, I found out that the Mail gem is the culprit - version 2.6.4 works alright, version 2.7.0 crashes with the ArgumentError above. Downgrading it solved the problem.

Thank you for your patient help and for Mailcatcher.
