### ISSUE TITLE
Messages containing special characters don't send

### ISSUE THREAD

**Issue by colinpickup** [sj26/mailcatcher#400]
I'm having an issue whereby special characters aren't sending. The message is UTF-8 encoded and appears to be sending the correct headers ("Content-Type: text/html; charset=utf-8"). 

I'm using:

`ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux-gnu]`

```
gem list

*** LOCAL GEMS ***

airbrussh (1.3.1, 1.3.0)
bigdecimal (1.4.3, default: 1.3.4)
capistrano (3.11.0)
capistrano-magento2 (0.8.7, 0.8.4)
cmath (default: 1.0.0)
concurrent-ruby (1.1.5, 1.0.5)
csv (3.0.5, default: 1.0.0)
daemons (1.3.1, 1.2.6)
date (2.0.0, default: 1.0.0)
dbm (default: 1.0.0)
did_you_mean (1.3.0, 1.2.0)
etc (1.0.1, default: 1.0.0)
eventmachine (1.2.7, 1.0.9.1)
fcntl (default: 1.0.0)
fiddle (default: 1.0.0)
fileutils (1.1.0, default: 1.0.2)
gdbm (default: 2.0.0)
i18n (1.6.0, 1.1.0)
io-console (0.4.7, default: 0.4.6)
ipaddr (1.2.2, default: 1.2.0)
json (2.2.0, default: 2.1.0)
mail (2.7.1, 2.7.0)
mailcatcher (0.7.1, 0.6.5)
mini_mime (1.0.1)
minitest (5.11.3, 5.10.3)
mustermann (1.0.3)
net-scp (2.0.0, 1.2.1)
net-ssh (5.2.0, 5.0.2)
net-telnet (0.2.0, 0.1.1)
openssl (2.1.2, default: 2.1.1)
power_assert (1.1.4, 0.2.7)
psych (3.1.0, default: 3.0.2)
rack (2.0.6, 1.6.10)
rack-protection (2.0.5, 1.5.5)
rake (12.3.2, 12.3.1)
rdoc (6.1.1, default: 6.0.1)
scanf (default: 1.0.0)                                                                                                               
sdbm (default: 1.0.0)                                                                                                                
sinatra (2.0.5, 1.4.8)                                                                                                               
skinny (0.2.4)                                                                                                                       
sqlite3 (1.4.0, 1.3.13)                                                                                                              
sshkit (1.18.2, 1.17.0)                                                                                                              
stringio (0.0.2, default: 0.0.1)                                                                                                     
strscan (default: 1.0.0)                                                                                                             
test-unit (3.3.0, 3.2.5)                                                                                                             
thin (1.7.2, 1.5.1)                                                                                                                  
tilt (2.0.9, 2.0.8)                                                                                                                  
webrick (default: 1.4.2)                                                                                                             
zlib (default: 1.0.0)
```
The exact character that's failing to send is the £ sign. The message I'm getting is:
```
/var/lib/gems/2.5.0/gems/mail-2.7.1/lib/mail/message.rb:2032:in `match': invalid byte sequence in US-ASCII (ArgumentError)
        from /var/lib/gems/2.5.0/gems/mail-2.7.1/lib/mail/message.rb:2032:in `match'
        from /var/lib/gems/2.5.0/gems/mail-2.7.1/lib/mail/message.rb:2032:in `set_envelope_header'
        from /var/lib/gems/2.5.0/gems/mail-2.7.1/lib/mail/message.rb:2132:in `init_with_string'
        from /var/lib/gems/2.5.0/gems/mail-2.7.1/lib/mail/message.rb:137:in `initialize'
        from /var/lib/gems/2.5.0/gems/mail-2.7.1/lib/mail/mail.rb:51:in `new'
        from /var/lib/gems/2.5.0/gems/mail-2.7.1/lib/mail/mail.rb:51:in `new'
        from /var/lib/gems/2.5.0/gems/mailcatcher-0.7.1/bin/catchmail:59:in `<top (required)>'
        from /usr/local/bin/catchmail:23:in `load'
        from /usr/local/bin/catchmail:23:in `<main>'
```
The headers of the message are:
```
Date: Fri, 26 Jul 2019 08:11:39 +0000
From: =?utf-8?Q?Sales?= <customerservice@localhost.com>
Bcc: web@localhost.com
MIME-Version: 1.0
Content-Type: text/html;
 charset="utf-8"
Content-Transfer-Encoding: 8bit
```
Changing the £ to &pound; works, but doing so where the html email is generated doesn't work - it seems to get decoded back into a £ unless done in core files of the framework I am using.

I tried getting rid of the line break and quotes in the Content-Type header, that didn't help. Can you provide any assistance?

Thanks,

Colin.

**Comment by sj26** [comment]
Hi Colin!

mailcatcher does not currently support content transfer encoding 8bit. Your mail library should be detecting this and using a different content transfer encoding. Maybe check your library?

Cheers,
Sam
