### ISSUE TITLE
Failed to send email with special letters (ø, å, etc.) in the email, e.g. bø@test.com

### ISSUE THREAD

**Issue by pikulsky** [sj26/mailcatcher#420]
```
*** Error receiving message: {:sender=>"<test@test.com>", :recipients=>["<b\xC3\xB8@test.com>"], ...tml>\r\n"}
    Exception: "\xC3" from ASCII-8BIT to UTF-8
    Backtrace:
       /usr/local/lib/ruby/2.4.0/json/common.rb:224:in `encode'
       /usr/local/lib/ruby/2.4.0/json/common.rb:224:in `generate'
       /usr/local/lib/ruby/2.4.0/json/common.rb:224:in `generate'
       mailcatcher (0.6.5) lib/mail_catcher/mail.rb:44:in `add_message'
       mailcatcher (0.6.5) lib/mail_catcher/smtp.rb:46:in `receive_message'
       eventmachine (1.0.9.1) lib/em/protocols/smtpserver.rb:558:in `process_data_line'
       eventmachine (1.0.9.1) lib/em/protocols/smtpserver.rb:196:in `receive_line'
       eventmachine (1.0.9.1) lib/em/protocols/linetext2.rb:66:in `receive_data'
       eventmachine (1.0.9.1) lib/eventmachine.rb:193:in `run_machine'
       eventmachine (1.0.9.1) lib/eventmachine.rb:193:in `run'
       mailcatcher (0.6.5) lib/mail_catcher.rb:173:in `run!'
       mailcatcher (0.6.5) bin/mailcatcher:5:in `<top (required)>'
       /usr/local/bundle/bin/mailcatcher:23:in `load'
       /usr/local/bundle/bin/mailcatcher:23:in `<main>'

```

**Comment by sj26** [comment]
Correct, sorry — SMTP does not support utf8 by default, it is an extension, and mailcatcher does not implement this extension. Your smtp client should notice this, and encode the parameters properly. If it does not, you're not using a correctly implemented smtp client.
