### ISSUE TITLE
NoMethodError - undefined method `match?' for nil:NilClass

### ISSUE THREAD

**Issue by zhengxiangyue** [sj26/mailcatcher#460]
Got this error when opening localhost:1080 in browser 
```
NoMethodError - undefined method `match?' for nil:NilClass:
 /Users/XiangyueZheng/.rbenv/versions/2.6.6/lib/ruby/2.6.0/time.rb:546:in `httpdate'
 /Users/XiangyueZheng/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/sinatra-1.2.8/lib/sinatra/base.rb:377:in `last_modified'
 /Users/XiangyueZheng/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/sinatra-1.2.8/lib/sinatra/base.rb:205:in `send_file'
 /Users/XiangyueZheng/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/sinatra-1.2.8/lib/sinatra/base.rb:804:in `static!'
 /Users/XiangyueZheng/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/sinatra-1.2.8/lib/sinatra/base.rb:855:in `dispatch!'
 /Users/XiangyueZheng/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/sinatra-1.2.8/lib/sinatra/base.rb:659:in `block in call!'
 /Users/XiangyueZheng/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/sinatra-1.2.8/lib/sinatra/base.rb:823:in `block in invoke'
 /Users/XiangyueZheng/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/sinatra-1.2.8/lib/sinatra/base.rb:823:in `catch'
 /Users/XiangyueZheng/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/sinatra-1.2.8/lib/sinatra/base.rb:823:in `invoke'
 /Users/XiangyueZheng/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/sinatra-1.2.8/lib/sinatra/base.rb:659:in `call!'
 /Users/XiangyueZheng/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/sinatra-1.2.8/lib/sinatra/base.rb:644:in `call'
 /Users/XiangyueZheng/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/rack-1.6.13/lib/rack/head.rb:13:in `call'
 /Users/XiangyueZheng/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/sinatra-1.2.8/lib/sinatra/base.rb:1295:in `block in call'
 /Users/XiangyueZheng/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/sinatra-1.2.8/lib/sinatra/base.rb:1326:in `synchronize'
 /Users/XiangyueZheng/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/sinatra-1.2.8/lib/sinatra/base.rb:1295:in `call'
 /Users/XiangyueZheng/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/rack-1.6.13/lib/rack/urlmap.rb:66:in `block in call'
 /Users/XiangyueZheng/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/rack-1.6.13/lib/rack/urlmap.rb:50:in `each'
 /Users/XiangyueZheng/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/rack-1.6.13/lib/rack/urlmap.rb:50:in `call'
 /Users/XiangyueZheng/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/rack-1.6.13/lib/rack/builder.rb:153:in `call'
 /Users/XiangyueZheng/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/mailcatcher-0.7.1/lib/mail_catcher/web.rb:24:in `call'
 /Users/XiangyueZheng/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/thin-1.5.1/lib/thin/connection.rb:81:in `block in pre_process'
 /Users/XiangyueZheng/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/thin-1.5.1/lib/thin/connection.rb:79:in `catch'
 /Users/XiangyueZheng/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/thin-1.5.1/lib/thin/connection.rb:79:in `pre_process'
 /Users/XiangyueZheng/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/thin-1.5.1/lib/thin/connection.rb:54:in `process'
 /Users/XiangyueZheng/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/thin-1.5.1/lib/thin/connection.rb:39:in `receive_data'
 /Users/XiangyueZheng/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/eventmachine-1.0.9.1/lib/eventmachine.rb:193:in `run_machine'
 /Users/XiangyueZheng/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/eventmachine-1.0.9.1/lib/eventmachine.rb:193:in `run'
 /Users/XiangyueZheng/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/mailcatcher-0.7.1/lib/mail_catcher.rb:190:in `run!'
 /Users/XiangyueZheng/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/mailcatcher-0.7.1/bin/mailcatcher:5:in `<top (required)>'
 /Users/XiangyueZheng/.rbenv/versions/2.6.6/bin/mailcatcher:23:in `load'
 /Users/XiangyueZheng/.rbenv/versions/2.6.6/bin/mailcatcher:23:in `<main>'
```

**Context:** 
How I installed `mailcatcher`:
I'm on M1 Silicon so this was the command I used to install mailcatcher:
```
gem install mailcatcher -- --with-cflags="-Wno-error=implicit-function-declaration"
```

How I stared the server:
```
mailcatcher --foreground
```

How I managed to solve the issue:
By using docker:
```
docker run -p 1025:1025 -p 1080:1080 <mailcatcher>
```

**Comment by sj26** [comment]
Sorry I'm not sure why this would happen, sounds like a ruby error within the state file server. I'm glad you've got a workaround. I'm not sure we can solve this practically, so I will close in favour of your workaround.
