### ISSUE TITLE
Exception: undefined method `length' for nil:NilClass

### ISSUE THREAD

**Issue by natasha1234567890** [sj26/mailcatcher#544]
```
Starting MailCatcher v0.8.2
==> smtp://0.0.0.0:1025
==> http://0.0.0.0:1080
*** Error receiving message: {:sender=>"rr@dd.com", :recipients=>["ss@ss.com"]}
    Exception: undefined method `length' for nil:NilClass
    Backtrace:
       mailcatcher (0.8.2) lib/mail_catcher/mail.rb:48:in `add_message'
       mailcatcher (0.8.2) lib/mail_catcher/smtp.rb:58:in `receive_message'
       eventmachine (1.0.9.1) lib/em/protocols/smtpserver.rb:558:in `process_data_line'
       eventmachine (1.0.9.1) lib/em/protocols/smtpserver.rb:196:in `receive_line'
       eventmachine (1.0.9.1) lib/em/protocols/linetext2.rb:66:in `receive_data'
       eventmachine (1.0.9.1) lib/eventmachine.rb:193:in `run_machine'
       eventmachine (1.0.9.1) lib/eventmachine.rb:193:in `run'
       mailcatcher (0.8.2) lib/mail_catcher.rb:180:in `run!'
       mailcatcher (0.8.2) bin/mailcatcher:6:in `<top (required)>'
       /usr/local/bundle/bin/mailcatcher:25:in `load'
       /usr/local/bundle/bin/mailcatcher:25:in `<main>'
    Please submit this as an issue at https://github.com/sj26/mailcatcher/issues
==> SMTP: Received message from 'll@cc.com' (29 bytes)
```

**Comment by sj26** [comment]
Sorry!

Looks like your message was missing a body.

Do you have a copy of the message you were trying to send?
