### ISSUE TITLE
`event_callback`: undefined method `close' for 9:Fixnum (NoMethodError)

### ISSUE THREAD

**Issue by neezer** [sj26/mailcatcher#62]
Here's what I'm doing:
1. Start mailcatcher on the command line via `mailcatcher`
2. Visit `http://localhost:1080`
3. Page loads, but server crashes with this error:

```
redtail git:master ❯ mailcatcher                                                                                                                             ⏎
Starting MailCatcher
==> smtp://127.0.0.1:1025
==> http://127.0.0.1:1080
/Users/evan/.rbenv/versions/1.9.3-p194-perf/lib/ruby/gems/1.9.1/gems/eventmachine-1.0.0/lib/eventmachine.rb:1441:in `event_callback': undefined method `close' for 9:Fixnum (NoMethodError)
    from /Users/evan/.rbenv/versions/1.9.3-p194-perf/lib/ruby/gems/1.9.1/gems/eventmachine-1.0.0/lib/eventmachine.rb:187:in `run_machine'
    from /Users/evan/.rbenv/versions/1.9.3-p194-perf/lib/ruby/gems/1.9.1/gems/eventmachine-1.0.0/lib/eventmachine.rb:187:in `run'
    from /Users/evan/.rbenv/versions/1.9.3-p194-perf/lib/ruby/gems/1.9.1/gems/mailcatcher-0.2.4/lib/mail_catcher.rb:21:in `run'
    from /Users/evan/.rbenv/versions/1.9.3-p194-perf/lib/ruby/gems/1.9.1/gems/mailcatcher-0.2.4/bin/mailcatcher:44:in `<top (required)>'
    from /Users/evan/.rbenv/versions/1.9.3-p194-perf/bin/mailcatcher:23:in `load'
    from /Users/evan/.rbenv/versions/1.9.3-p194-perf/bin/mailcatcher:23:in `<main>'
```

What gives?

**Comment by santosham** [comment]
plz same error need ful help to me
